"""hugger — FastHTML app: SSR web UI + token-authenticated JSON API.

Hardened for internet exposure: argon2 password login, signed session cookies,
per-IP login throttle, CSRF tokens on state-changing UI routes, Bearer-token API
for the browser extension, security headers + TrustedHost, optional HSTS/CORS.
"""
from __future__ import annotations

import json
import os
import secrets

from fasthtml.common import *  # noqa: F403  (FT tags, fast_app, serve, Beforeware, RedirectResponse)
from starlette.middleware import Middleware
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.middleware.cors import CORSMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware
from starlette.responses import JSONResponse

from . import auth, hub, jobs, metadata, store, util
from .config import ARCHIVE_DIR, cfg
from .hub import search_models

VERSION = "0.1.0"

# --- bootstrap secrets / password ----------------------------------------

def _bootstrap_password() -> None:
    """Ensure a password exists. Env HUGGER_PASSWORD sets/updates it; otherwise a
    random one is generated, printed once, and flagged so the user is forced to
    change it on first login."""
    env_pw = os.environ.get("HUGGER_PASSWORD")
    if env_pw:
        auth.set_password(env_pw, autogenerated=False)
        return
    if not auth.has_password():
        generated = secrets.token_urlsafe(12)
        auth.set_password(generated, autogenerated=True)
        banner = (
            "=" * 60
            + "\n hugger: no password set — generated an initial one:"
            + f"\n   PASSWORD: {generated}"
            + "\n   You'll be required to change it on first login.\n"
            + "=" * 60
        )
        print(banner, flush=True)


# --- helpers -------------------------------------------------------------

def human_size(n: int) -> str:
    f = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if f < 1024 or unit == "TB":
            return f"{f:.0f} {unit}" if unit == "B" else f"{f:.1f} {unit}"
        f /= 1024
    return f"{f:.1f} TB"


def _csrf_value(req, form_val: str | None) -> str | None:
    return req.headers.get("x-csrf-token") or form_val


# --- interactive UI helpers ----------------------------------------------

def action_button(label: str, *, busy: str | None = None, **kw):
    """A button that, while its HTMX request is in flight, recolors and shows a
    busy label (e.g. "Download" -> "Downloading…"). CSS toggles idle/busy spans."""
    if busy is None:
        busy = label.rstrip(".… ") + "…"
    return Button(Span(label, cls="idle"), Span(busy, cls="busy"), **kw)


def modal(title: str, *content):
    """Overlay wrapper; swapped into the page-level #modal container."""
    return Div(
        Div(
            Div(H3(title),
                Button("✕", cls="modal-close", hx_get="/ui/close",
                       hx_target="#modal", hx_swap="innerHTML"),
                cls="modal-head"),
            *content,
            cls="modal-card",
        ),
        cls="modal-overlay",
    )


def _modal_close_oob():
    """Out-of-band empty #modal to dismiss the modal after an action."""
    return Div(id="modal", hx_swap_oob="true")


def _modal_oob(*content):
    """Out-of-band re-render of #modal (e.g. to keep a picker open with an error)."""
    return Div(*content, id="modal", hx_swap_oob="true")


def file_list(files: list[dict], *, action: str, submit_buttons: list, hidden: dict | None = None,
              preselect=None, statuses: dict | None = None, removable_repo: str | None = None,
              disabled=None):
    """Reusable file picker: checkbox + path + size, optional status + per-file
    remove. `disabled` paths can't be selected (e.g. files currently downloading).
    `files` items: {path, size}. Returns a Form posting to `action`."""
    preselect = preselect if preselect is not None else {f["path"] for f in files}
    disabled = disabled or set()
    head = [Th(""), Th("File"), Th("Size")]
    if statuses is not None:
        head.append(Th("Status"))
    if removable_repo:
        head.append(Th(""))
    rows = []
    for f in files:
        is_disabled = f["path"] in disabled
        cells = [
            Td(Input(type="checkbox", name="files", value=f["path"],
                     checked=(f["path"] in preselect and not is_disabled), disabled=is_disabled)),
            Td(f["path"], cls="mono"),
            Td(human_size(f["size"]), cls="muted"),
        ]
        status = statuses.get(f["path"]) if statuses is not None else None
        if statuses is not None:
            ok = status in ("downloaded", "unchanged")
            cells.append(Td(Span(status, cls="badge current" if ok else "badge update")))
        if removable_repo:
            rm = (action_button("Remove", cls="danger", hx_post=f"/ui/file-remove/{removable_repo}",
                                 hx_vals=json.dumps({"path": f["path"]}), hx_target="#managelist", hx_swap="outerHTML")
                  if status == "downloaded" else "")
            cells.append(Td(rm))
        rows.append(Tr(*cells))
    return Form(
        *[Input(type="hidden", name=k, value=v) for k, v in (hidden or {}).items()],
        Div(Table(Thead(Tr(*head)), Tbody(*rows)), cls="filelist"),
        Div(*submit_buttons, cls="row"),
        hx_post=action, hx_target="#jobs", hx_swap="outerHTML",
    )


def file_statuses(repo_id: str, files: list[dict]):
    """Per-file status (downloaded / downloading / missing) + the set of paths
    that are currently downloading (and so can't be selected)."""
    rec = store.get_archive(repo_id)
    downloading = jobs.manager.active_download_files(repo_id)
    statuses = {}
    for f in files:
        if rec and metadata.file_downloaded(rec["path"], f["path"], f["size"]):
            statuses[f["path"]] = "downloaded"
        elif f["path"] in downloading:
            statuses[f["path"]] = "downloading"
        else:
            statuses[f["path"]] = "missing"
    locked = {p for p, s in statuses.items() if s == "downloading"}
    return statuses, locked


# --- security middleware -------------------------------------------------

class SecurityHeaders(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        if request.method in ("GET", "HEAD"):
            request.scope["headers"] = [
                h for h in request.scope["headers"] if h[0] != b"content-type"
            ]
        resp = await call_next(request)
        resp.headers["X-Content-Type-Options"] = "nosniff"
        resp.headers["X-Frame-Options"] = "DENY"
        resp.headers["Referrer-Policy"] = "no-referrer"
        # ponytail: moderate CSP — allows inline (htmx attrs) + the CDN FastHTML
        # loads htmx from. Tighten to 'self' if you self-host htmx.
        resp.headers["Content-Security-Policy"] = (
            "default-src 'self'; "
            "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://unpkg.com; "
            "style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'"
        )
        if cfg.https_only:
            resp.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
        return resp


def _middleware() -> list:
    mw = [Middleware(TrustedHostMiddleware, allowed_hosts=cfg.allowed_hosts)]
    if cfg.allowed_origins:
        mw.append(
            Middleware(
                CORSMiddleware,
                allow_origins=cfg.allowed_origins,
                allow_methods=["GET", "POST", "DELETE"],
                allow_headers=["authorization", "x-hugger-token", "content-type"],
            )
        )
    mw.append(Middleware(SecurityHeaders))
    return mw


# --- auth gate -----------------------------------------------------------

def _before(req, sess):
    path = req.url.path
    if path.startswith("/api/"):
        if not auth.verify_token(auth.bearer_from_request(req)):
            return JSONResponse({"error": "unauthorized"}, status_code=401)
        return  # token ok -> allow
    if not sess.get("auth"):
        return RedirectResponse("/login", status_code=303)
    # Force an autogenerated password to be changed before anything else.
    if auth.must_change_password() and path not in ("/change-password", "/logout"):
        return RedirectResponse("/change-password", status_code=303)


beforeware = Beforeware(
    _before,
    skip=[r"/favicon\.ico", r"/static/.*", r".*\.css", r".*\.js", "/login"],
)

# --- theme ---------------------------------------------------------------

THEME = Style(
    """
    :root{
      --bg:#FFF8E1; --surface:#FFECB3; --surface-2:#FFE082;
      --ink:#4E342E; --muted:#8D6E63;
      --accent:#FB8C00; --accent-2:#F4511E; --danger:#E53935; --ok:#2E7D32;
      --radius:12px;
    }
    *{box-sizing:border-box}
    body{margin:0;background:var(--bg);color:var(--ink);
      font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;line-height:1.5}
    header{background:linear-gradient(90deg,var(--accent),var(--accent-2));
      color:#fff;padding:.8rem 1.2rem;display:flex;align-items:center;gap:1rem}
    header h1{margin:0;font-size:1.25rem}
    header nav{margin-left:auto;display:flex;gap:.6rem}
    header a{color:#fff;text-decoration:none;opacity:.95;font-weight:600}
    main{max-width:980px;margin:0 auto;padding:1.2rem}
    .card{background:var(--surface);border:1px solid var(--surface-2);
      border-radius:var(--radius);padding:1rem 1.2rem;margin-bottom:1.2rem}
    h2{margin-top:0;color:var(--accent-2)}
    input[type=text],input[type=password]{padding:.55rem .7rem;border:1px solid var(--surface-2);
      border-radius:8px;background:#fffdf6;font-size:1rem;min-width:16rem}
    button,.btn{cursor:pointer;border:none;border-radius:8px;padding:.55rem .9rem;
      font-weight:600;font-size:.95rem;background:var(--accent);color:#fff}
    button:hover{background:var(--accent-2)}
    button.danger{background:var(--danger)}
    button.ghost{background:transparent;color:var(--accent-2);border:1px solid var(--accent)}
    table{width:100%;border-collapse:collapse}
    th,td{text-align:left;padding:.5rem .4rem;border-bottom:1px solid var(--surface-2);font-size:.92rem}
    th{color:var(--muted);font-weight:600}
    .row{display:flex;gap:.6rem;align-items:center;flex-wrap:wrap}
    .badge{display:inline-block;padding:.15rem .5rem;border-radius:999px;font-size:.78rem;font-weight:700}
    .badge.update{background:var(--danger);color:#fff}
    .badge.current{background:var(--surface-2);color:var(--muted)}
    .mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.85em}
    .muted{color:var(--muted)}
    progress{width:100%;height:14px;accent-color:var(--accent-2)}
    .job{margin:.5rem 0}
    .err{color:var(--danger);font-weight:600}
    a.link{color:var(--accent-2)}
    .stat-num{font-weight:800;color:var(--accent-2)}
    main ul{list-style:none;padding-left:0;margin:.6rem 0}
    main li{padding:.4rem 0;border-bottom:1px solid var(--surface-2)}
    .notice{background:#FFF3E0;border:1px solid var(--accent);border-left:5px solid var(--accent);
      border-radius:8px;padding:.7rem 1rem;margin-bottom:1.2rem;color:var(--ink)}
    .notice a{color:var(--accent-2);font-weight:700}
    /* interactive buttons: while their request is in flight, recolor + show busy label */
    button{transition:background .12s ease}
    button .busy{display:none}
    button.htmx-request{background:var(--accent-2);cursor:progress}
    button.htmx-request.danger{background:#B71C1C}
    a.btn{text-decoration:none;display:inline-block;font-size:.95rem}
    a.btn.ghost{background:transparent;color:var(--accent-2);border:1px solid var(--accent)}
    button.htmx-request .idle{display:none}
    button.htmx-request .busy{display:inline}
    /* modal */
    .modal-overlay{position:fixed;inset:0;background:rgba(40,20,0,.45);display:flex;
      align-items:center;justify-content:center;z-index:1000;padding:1rem}
    .modal-card{background:var(--bg);border:1px solid var(--surface-2);border-radius:14px;
      max-width:680px;width:100%;max-height:86vh;overflow:auto;padding:1.2rem 1.4rem;
      box-shadow:0 24px 70px rgba(0,0,0,.4)}
    .modal-head{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-bottom:.4rem}
    .modal-head h3{margin:0;color:var(--accent-2)}
    .modal-close{background:transparent;color:var(--muted);font-size:1.3rem;line-height:1;padding:.1rem .5rem}
    .modal-close:hover{background:var(--surface-2)}
    .filelist{max-height:48vh;overflow:auto;margin:.4rem 0}
    """
)

app, rt = fast_app(
    secret_key=cfg.secret_key,
    before=beforeware,
    middleware=_middleware(),
    pico=False,
    hdrs=(THEME,),
    # On graceful shutdown, mark in-flight jobs queued (not failed) so they resume.
    on_shutdown=[jobs.manager.shutdown],
)


# --- shared fragments ----------------------------------------------------

def search_results(models: list[dict], query: str = ""):
    """Search results rendered as a modal; each row opens the file picker modal."""
    if not models:
        return modal(f"Search · {query}".rstrip(" ·"), P("No results.", cls="muted"))
    rows = []
    for m in models:
        rows.append(
            Tr(
                Td(A(m["id"], href=f"https://huggingface.co/{m['id']}", target="_blank", cls="link mono")),
                Td(f"{m['downloads']:,}", cls="muted"),
                Td(f"♥ {m['likes']}", cls="muted"),
                Td(
                    action_button(
                        "⤓ Archive…", busy="Opening…",
                        hx_get="/ui/files",
                        hx_vals=json.dumps({"repo_id": m["id"]}),
                        hx_include="#target-store",
                        hx_target="#modal",
                        hx_swap="innerHTML",
                    )
                ),
            )
        )
    return modal(
        f"Search · {query}".rstrip(" ·"),
        Div(Table(Thead(Tr(Th("Model"), Th("Downloads"), Th("Likes"), Th())), Tbody(*rows)), cls="filelist"),
    )


def _job_verb(j) -> str:
    return "move" if j.type == "move" else "download"


def jobs_fragment(notice: str | None = None):
    active = jobs.manager.active()
    finished = [j for j in jobs.manager.recent() if j.status in ("done", "error")]
    items = []
    for j in active:
        kind = "⇄ move" if j.type == "move" else "⤓ download"
        controls = []
        if j.status == "paused":
            controls.append(action_button("Resume", cls="ghost", hx_post=f"/ui/jobs/{j.id}/resume",
                                          hx_target="#jobs", hx_swap="outerHTML"))
            if j.type == "download":  # only paused downloads can re-pick files
                controls.append(action_button("Edit files", busy="Opening…",
                                              hx_get=f"/ui/jobs/{j.id}/files",
                                              hx_target="#modal", hx_swap="innerHTML"))
            state = Span(" paused", cls="muted")
        else:
            controls.append(action_button("Pause", cls="ghost", hx_post=f"/ui/jobs/{j.id}/pause",
                                          hx_target="#jobs", hx_swap="outerHTML"))
            state = Span(f" {j.percent}%", cls="muted")
        items.append(
            Div(
                Div(Span(f"{kind} ", cls="muted"), Span(j.repo_id, cls="mono"), state),
                Progress(value=str(j.done_bytes), max=str(max(j.total_bytes, 1))),
                Div(
                    Span(f"{human_size(j.done_bytes)} / {human_size(j.total_bytes)}", cls="muted"),
                    *controls, cls="row",
                ),
                cls="job",
            )
        )
    for j in finished:
        if j.status == "error":
            items.append(Div(Span(j.repo_id, cls="mono"), Span(f" {_job_verb(j)} failed: ", cls="err"), Span(j.error or "", cls="err"), cls="job"))
        else:
            items.append(Div(Span("✓ ", cls=""), Span(j.repo_id, cls="mono"), Span(f" {_job_verb(j)}d", cls="muted"), cls="job"))
    # Poll while anything is running; paused jobs don't need polling.
    poll = "load, every 1s" if any(j.status in ("queued", "running") for j in active) else "none"
    inner = items or [P("No active jobs.", cls="muted")]
    if any(j.type == "download" and j.status in ("queued", "running") for j in active):
        inner.append(P("ℹ︎ Download progress is reported by huggingface_hub: "
                       "per-chunk on the classic path, in ~64 MB steps over Xet — "
                       "so large files advance in jumps. (Set HF_HUB_DISABLE_XET=1 "
                       "for finer steps.)", cls="muted"))
    if notice:
        inner = [P(notice, cls="err"), *inner]
    return Div(
        *inner,
        id="jobs",
        hx_get="/ui/jobs",
        hx_trigger=poll,
        hx_swap="outerHTML",
    )


def _short(sha: str | None) -> str:
    return (sha or "")[:8]


def _move_control(repo_id: str, current_store_id: str | None, stores: list[dict]):
    others = [s for s in stores if s["id"] != current_store_id]
    if not others:
        # Nowhere to move to yet — point the user at adding a store.
        return A("Move…", href="/stores", cls="link muted", title="Add another store to move into")
    return Form(
        Select(*[Option(s["name"], value=s["id"]) for s in others], name="store_id"),
        action_button("Move", cls="ghost"),
        hx_post=f"/ui/move/{repo_id}", hx_target="#jobs", hx_swap="outerHTML",
        cls="row",
    )


def archives_fragment():
    rows = []
    for a in store.list_archives():
        badge = (
            Span("update available", cls="badge update")
            if a["update_available"]
            else Span("current", cls="badge current")
        )
        rows.append(
            Tr(
                Td(A(a["repo_id"], href=f"https://huggingface.co/{a['repo_id']}", target="_blank", cls="link mono")),
                Td(a.get("store_name") or "—", cls="muted"),
                Td(human_size(a["size_bytes"]), cls="muted"),
                Td(_short(a["sha"]), cls="mono muted"),
                Td(badge),
                Td(
                    Div(
                        A("Manage", href=f"/manage/{a['repo_id']}", cls="btn ghost"),
                        (action_button("Update…", busy="Checking…", hx_get=f"/ui/update/{a['repo_id']}",
                                       hx_target="#modal", hx_swap="innerHTML")
                         if a["update_available"] else
                         action_button("Check", hx_post=f"/ui/check/{a['repo_id']}",
                                       hx_target="#archives", hx_swap="outerHTML", cls="ghost")),
                        action_button("Delete", cls="danger",
                                      hx_post=f"/ui/delete/{a['repo_id']}", hx_target="#archives", hx_swap="outerHTML",
                                      hx_confirm=f"Delete archive {a['repo_id']} from disk?"),
                        cls="row",
                    )
                ),
            )
        )
    body = (
        Table(
            Thead(Tr(Th("Model"), Th("Store"), Th("Size"), Th("Commit"), Th("Status"), Th("Actions"))),
            Tbody(*rows),
        )
        if rows
        else P("Nothing archived yet. Search above or use the browser extension.", cls="muted")
    )
    header = Div(
        H2("Archived models"),
        action_button("Check all for updates", busy="Checking…", cls="ghost",
               hx_post="/ui/check-all", hx_target="#archives", hx_swap="outerHTML"),
        cls="row",
    )
    return Div(header, body, id="archives", hx_get="/ui/archives",
               hx_trigger="every 5s", hx_swap="outerHTML")


def summary_fragment():
    """Compact recent-activity view for the dashboard (full table lives at /archives)."""
    archives = store.list_archives()
    total = len(archives)
    size = sum(a["size_bytes"] for a in archives)
    updates = sum(1 for a in archives if a["update_available"])

    stats = Div(
        Span(f"{total}", cls="stat-num"), Span(" archived", cls="muted"),
        Span(" · ", cls="muted"), Span(human_size(size), cls="stat-num"),
        Span(" on disk", cls="muted"),
        *([Span(" · ", cls="muted"), Span(f"{updates}", cls="stat-num"),
           Span(" update(s) available", cls="muted")] if updates else []),
        cls="row",
    )
    if archives:
        recent = [
            Li(
                A(a["repo_id"], href=f"https://huggingface.co/{a['repo_id']}",
                  target="_blank", cls="link mono"),
                Span(f" · {human_size(a['size_bytes'])}", cls="muted"),
                (Span(" · update available", cls="badge update") if a["update_available"] else ""),
            )
            for a in archives[:5]
        ]
        recent_list = Ul(*recent)
    else:
        recent_list = P("Nothing archived yet. Search above or use the browser extension.", cls="muted")

    return Div(
        H2("Recent activity"),
        stats,
        recent_list,
        A("View all archives →", href="/archives", cls="link"),
        id="summary", hx_get="/ui/summary", hx_trigger="every 5s", hx_swap="outerHTML",
    )


def page(*content, sess=None):
    csrf = auth.csrf_token(sess) if sess is not None else ""
    return Title("hugger"), Div(
        Header(
            H1("🤗 hugger"),
            Nav(
                A("Home", href="/"),
                A("Archives", href="/archives"),
                A("Jobs", href="/jobs"),
                A("Stores", href="/stores"),
                A("Settings", href="/settings"),
                A("Logout", href="/logout"),
            ),
        ),
        Main(*content),
        Div(id="modal"),  # action modals (file lists) render here
        id="app",
        hx_headers=json.dumps({"X-CSRF-Token": csrf}),
    )


@rt("/ui/close", methods=["GET"])
def ui_close():
    return Div(id="modal")


# --- pages ---------------------------------------------------------------

def store_selector():
    """Target-store control for new downloads (hidden input if there's only one)."""
    stores = store.list_stores()
    if len(stores) <= 1:
        sid = stores[0]["id"] if stores else ""
        return Input(type="hidden", id="target-store", name="store_id", value=sid)
    default = next((s for s in stores if s["is_default"]), stores[0])
    return Div(
        Span("Target store: ", cls="muted"),
        Select(
            *[Option(s["name"], value=s["id"], selected=(s["id"] == default["id"])) for s in stores],
            id="target-store", name="store_id",
        ),
        cls="row",
    )


@rt("/")
def index(sess):
    search = Div(
        H2("Find a model"),
        Form(
            Input(type="text", name="q", placeholder="e.g. llama, bert, whisper…"),
            action_button("Search", busy="Searching…"),
            hx_post="/ui/search", hx_include="#target-store", hx_target="#modal", hx_swap="innerHTML",
        ),
        cls="card",
    )
    manual = Form(
        Input(type="text", name="repo_id", placeholder="org/model — archive by id"),
        action_button("⤓ Archive…", busy="Opening…"),
        hx_get="/ui/files", hx_include="#target-store", hx_target="#modal", hx_swap="innerHTML",
        cls="row",
    )
    downloads = Div(
        H2("Downloads"), store_selector(), manual, jobs_fragment(), cls="card",
    )
    blocks = []
    if hub.hf_token_source() == "none":
        blocks.append(Div(
            "⚠️ No HuggingFace token set. ",
            A("Add one in Settings", href="/settings"),
            " for faster downloads and to avoid rate limits.",
            cls="notice",
        ))
    blocks += [search, downloads, Div(summary_fragment(), cls="card")]
    return page(*blocks, sess=sess)


@rt("/archives")
def archives_page(sess):
    # Include the jobs panel so Move actions (which swap #jobs) have a target and
    # their progress is visible right here.
    return page(
        Div(archives_fragment(), cls="card"),
        Div(H2("Jobs"), jobs_fragment(), cls="card"),
        sess=sess,
    )


@rt("/login", methods=["GET"])
def login_form(req, error: str = ""):
    msg = P(error, cls="err") if error else ""
    return Title("hugger · login"), Div(
        Header(H1("🤗 hugger")),
        Main(
            Div(
                H2("Sign in"),
                msg,
                Form(
                    Input(type="password", name="password", placeholder="password", autofocus=True),
                    Button("Sign in"),
                    method="post", action="/login",
                ),
                cls="card",
            )
        ),
        id="app",
    )


@rt("/login", methods=["POST"])
def login(req, sess, password: str = ""):
    ip = req.client.host if req.client else "?"
    locked = auth.is_locked(ip)
    if locked:
        return RedirectResponse(f"/login?error=Too+many+attempts.+Try+again+in+{locked}s", status_code=303)
    if auth.verify_password(password):
        auth.record_success(ip)
        sess["auth"] = True
        auth.csrf_token(sess)  # mint a CSRF token for this session
        dest = "/change-password" if auth.must_change_password() else "/"
        return RedirectResponse(dest, status_code=303)
    auth.record_failure(ip)
    return RedirectResponse("/login?error=Invalid+password", status_code=303)


@rt("/change-password", methods=["GET"])
def change_password_form(sess, error: str = ""):
    forced = auth.must_change_password()
    msg = P(error, cls="err") if error else ""
    note = (
        P("Your password was generated automatically — choose a new one to continue.", cls="muted")
        if forced else ""
    )
    return Title("hugger · change password"), Div(
        Header(H1("🤗 hugger")),
        Main(
            Div(
                H2("Set a new password"),
                note, msg,
                Form(
                    Input(type="password", name="new", placeholder="new password", autofocus=True),
                    Input(type="password", name="confirm", placeholder="confirm new password"),
                    Button("Save password"),
                    method="post", action="/change-password",
                ),
                cls="card",
            )
        ),
        id="app",
        hx_headers=json.dumps({"X-CSRF-Token": auth.csrf_token(sess)}),
    )


@rt("/change-password", methods=["POST"])
def change_password(sess, new: str = "", confirm: str = ""):
    if len(new) < 6:
        return RedirectResponse("/change-password?error=Password+too+short+(min+6)", status_code=303)
    if new != confirm:
        return RedirectResponse("/change-password?error=Passwords+do+not+match", status_code=303)
    auth.set_password(new, autogenerated=False)  # clears the must-change flag
    return RedirectResponse("/", status_code=303)


@rt("/logout")
def logout(sess):
    sess.clear()
    return RedirectResponse("/login", status_code=303)


# --- UI fragments (HTMX, session + CSRF) ---------------------------------

def _guard_csrf(req, sess, csrf):
    return auth.csrf_ok(sess, _csrf_value(req, csrf))


@rt("/ui/search", methods=["POST"])
def ui_search(req, sess, q: str = "", csrf: str = ""):
    if not _guard_csrf(req, sess, csrf):
        return modal("Search", P("Session expired, reload the page.", cls="err"))
    return search_results(search_models(q), query=q)


def _archive_modal(repo_id: str, store_id: str, notice: str | None = None):
    """The Archive file-picker modal (shows total size + an optional error)."""
    try:
        info = hub.repo_files(repo_id)
    except Exception as e:
        return modal("Archive", P(f"Could not list files for {repo_id}: {e}", cls="err"))
    statuses, locked = file_statuses(repo_id, info["files"])
    total = sum(f["size"] for f in info["files"])
    head = [P(notice, cls="err")] if notice else []
    head.append(P(f"Total {human_size(total)} · {len(info['files'])} files", cls="muted"))
    form = file_list(
        info["files"], action="/ui/archive",
        hidden={"repo_id": repo_id, "store_id": store_id or ""}, statuses=statuses, disabled=locked,
        submit_buttons=[
            action_button("⤓ Download all", name="mode", value="all"),
            action_button("⤓ Download selected", name="mode", value="selected", cls="ghost"),
        ],
    )
    return modal(f"Archive {repo_id}", *head, form)


@rt("/ui/files", methods=["GET"])
def ui_files(req, sess, repo_id: str = "", store_id: str = ""):
    repo_id = repo_id.strip()
    if not repo_id:
        return Div(id="modal")
    return _archive_modal(repo_id, store_id)


@rt("/ui/archive", methods=["POST"])
async def ui_archive(req, sess):
    form = await req.form()
    if not auth.csrf_ok(sess, _csrf_value(req, form.get("csrf"))):
        return Div(P("Session expired, reload the page.", cls="err"), id="jobs")
    repo_id = (form.get("repo_id") or "").strip()
    store_id = (form.get("store_id") or "").strip() or None
    selected = None if (form.get("mode") or "all") == "all" else form.getlist("files")
    if repo_id:
        try:
            jobs.manager.start_download(repo_id, store_id=store_id, selected=selected)
        except (jobs.InsufficientSpace, jobs.Busy) as e:
            # Keep the picker open and show the error there, not in the jobs card.
            return jobs_fragment(), _modal_oob(_archive_modal(repo_id, store_id, notice=f"⚠️ {e}"))
        except Exception as e:
            return jobs_fragment(), _modal_oob(_archive_modal(repo_id, store_id, notice=f"⚠️ {type(e).__name__}: {e}"))
    return jobs_fragment(), _modal_close_oob()


@rt("/ui/move/{repo_id:path}", methods=["POST"])
def ui_move(req, sess, repo_id: str, store_id: str = "", csrf: str = ""):
    if _guard_csrf(req, sess, csrf) and store_id:
        try:
            jobs.manager.start_move(repo_id, store_id)
        except (jobs.InsufficientSpace, jobs.Busy) as e:
            return jobs_fragment(notice=f"⚠️ {e}")
        except KeyError:
            pass
    return jobs_fragment()


@rt("/ui/jobs/{job_id}/pause", methods=["POST"])
def ui_job_pause(req, sess, job_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        jobs.manager.pause(job_id)
    return jobs_fragment()


@rt("/ui/jobs/{job_id}/resume", methods=["POST"])
def ui_job_resume(req, sess, job_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        jobs.manager.resume(job_id)
    return jobs_fragment()


@rt("/ui/jobs/{job_id}/files", methods=["GET"])
def ui_job_files(req, sess, job_id: str):
    job = jobs.manager.get(job_id)
    if not job or job.type != "download":
        return Div(id="modal")
    try:
        info = hub.repo_files(job.repo_id, job.revision)
    except Exception as e:
        return modal("Edit files", P(f"Could not list files: {e}", cls="err"))
    st = store.get_store(job.store_id)
    meta = metadata.read(jobs.store_repo_path(st["path"], job.repo_id)) if st else None
    selected = set(meta["selected"]) if meta else {f["path"] for f in info["files"]}
    form = file_list(
        info["files"], action=f"/ui/jobs/{job_id}/files", preselect=selected,
        submit_buttons=[action_button("Save selection")],
    )
    return modal(f"Files for paused download · {job.repo_id}", form)


@rt("/ui/jobs/{job_id}/files", methods=["POST"])
async def ui_job_files_save(req, sess):
    form = await req.form()
    if auth.csrf_ok(sess, _csrf_value(req, form.get("csrf"))):
        jobs.manager.update_selected(req.path_params["job_id"], form.getlist("files"))
    return jobs_fragment(), _modal_close_oob()


def manage_list_fragment(repo_id: str):
    """The reusable file list for the manage page (download missing / remove)."""
    rec = store.get_archive(repo_id)
    if not rec:
        return Div(P("Not archived.", cls="muted"), id="managelist")
    try:
        info = hub.repo_files(repo_id, rec["revision"])
    except Exception as e:
        return Div(P(f"Could not list files: {e}", cls="err"), id="managelist")
    statuses, locked = file_statuses(repo_id, info["files"])
    preselect = {p for p, s in statuses.items() if s == "missing"}  # default: fetch missing
    form = file_list(
        info["files"], action=f"/ui/manage/{repo_id}", statuses=statuses,
        preselect=preselect, removable_repo=repo_id, disabled=locked,
        submit_buttons=[action_button("⤓ Download selected")],
    )
    return Div(form, id="managelist")


@rt("/manage/{repo_id:path}", methods=["GET"])
def manage_page(req, sess, repo_id: str):
    rec = store.get_archive(repo_id)
    if not rec:
        return page(Div(P("Not archived.", cls="muted"), cls="card"), sess=sess)
    move = _move_control(repo_id, rec.get("store_id"), store.list_stores())
    info = Div(
        H2(f"Manage {repo_id}"),
        P("Store: ", Span(rec.get("store_name") or "—", cls="mono"),
          " · ", Span(f"{rec['n_downloaded']}/{rec['n_files']} files", cls="muted"),
          " · ", Span(human_size(rec["size_bytes"]), cls="muted")),
        Div(Span("Move to another store: ", cls="muted"), move, cls="row"),
        A("← Back to archives", href="/archives", cls="link"),
        cls="card",
    )
    return page(
        info,
        Div(manage_list_fragment(repo_id), cls="card"),
        Div(H2("Jobs"), jobs_fragment(), cls="card"),
        sess=sess,
    )


@rt("/ui/manage/{repo_id:path}", methods=["POST"])
async def ui_manage_download(req, sess):
    form = await req.form()
    repo_id = req.path_params["repo_id"]
    if auth.csrf_ok(sess, _csrf_value(req, form.get("csrf"))):
        files = form.getlist("files")
        rec = store.get_archive(repo_id)
        if files and rec:
            try:
                jobs.manager.start_download(repo_id, rec["revision"], store_id=rec["store_id"], selected=files)
            except (jobs.InsufficientSpace, jobs.Busy) as e:
                return jobs_fragment(notice=f"⚠️ {e}")
    return jobs_fragment()


@rt("/ui/file-remove/{repo_id:path}", methods=["POST"])
async def ui_file_remove(req, sess):
    form = await req.form()
    repo_id = req.path_params["repo_id"]
    if auth.csrf_ok(sess, _csrf_value(req, form.get("csrf"))):
        path = form.get("path")
        if path:
            jobs.manager.remove_file(repo_id, path)
    return manage_list_fragment(repo_id)


def _update_modal(repo_id: str, notice: str | None = None):
    try:
        v = jobs.manager.verify(repo_id)
    except KeyError:
        return modal("Update", P("Not archived.", cls="muted"))
    except Exception as e:
        return modal("Update", P(f"Verify failed: {e}", cls="err"))
    changed = set(v["changed"]) | set(v["missing"])
    statuses = {f["path"]: f["status"] for f in v["files"]}
    buttons = [action_button(f"⟳ Update changed ({len(changed)})", name="mode", value="selected")]
    if v["all_present"]:
        buttons.append(action_button("⟳ Re-download all", name="mode", value="all", cls="ghost"))
    form = file_list(
        v["files"], action=f"/ui/update/{repo_id}", hidden={"repo_id": repo_id},
        statuses=statuses, preselect=changed, submit_buttons=buttons,
    )
    head = [P(notice, cls="err")] if notice else []
    head.append(P(f"{len(changed)} file(s) changed or missing.", cls="muted"))
    return modal(f"Update {repo_id}", *head, form)


@rt("/ui/update/{repo_id:path}", methods=["GET"])
def ui_update(req, sess, repo_id: str):
    return _update_modal(repo_id)


@rt("/ui/update/{repo_id:path}", methods=["POST"])
async def ui_update_apply(req, sess):
    form = await req.form()
    repo_id = req.path_params["repo_id"]
    if auth.csrf_ok(sess, _csrf_value(req, form.get("csrf"))):
        rec = store.get_archive(repo_id)
        if rec:
            selected = None if (form.get("mode") or "selected") == "all" else form.getlist("files")
            try:
                jobs.manager.start_download(repo_id, rec["revision"], store_id=rec["store_id"], selected=selected)
            except (jobs.InsufficientSpace, jobs.Busy) as e:
                return jobs_fragment(), _modal_oob(_update_modal(repo_id, notice=f"⚠️ {e}"))
    return jobs_fragment(), _modal_close_oob()


@rt("/ui/jobs", methods=["GET"])
def ui_jobs():
    return jobs_fragment()


def job_history_fragment():
    names = {s["id"]: s["name"] for s in store.list_stores()}
    rows = []
    for j in store.recent_jobs():
        badge = Span(j["status"], cls="badge update" if j["status"] == "error" else "badge current")
        detail = j["error"] or ""
        if j["status"] == "retried" and j.get("retried_by"):
            detail = f"→ retried as {j['retried_by']}"
        retry = (action_button("Retry", busy="Restarting…", cls="ghost",
                               hx_post=f"/ui/jobs/{j['id']}/retry", hx_target="#jobhistory", hx_swap="outerHTML")
                 if j["status"] == "error" else "")
        rows.append(Tr(
            Td("⇄ move" if j["type"] == "move" else "⤓ download", cls="muted"),
            Td(j["repo_id"], cls="mono"),
            Td(names.get(j["store_id"]) or "—", cls="muted"),
            Td(badge),
            Td(detail[:90], cls="err" if detail else "muted"),
            Td((j["updated_at"] or "")[:19].replace("T", " "), cls="muted mono"),
            Td(retry),
        ))
    body = (Table(Thead(Tr(Th("Type"), Th("Model"), Th("Store"), Th("Status"),
                           Th("Detail"), Th("Updated (UTC)"), Th(""))), Tbody(*rows))
            if rows else P("No jobs yet.", cls="muted"))
    header = Div(
        H2("Job history"),
        action_button("Clear finished", busy="Clearing…", cls="ghost",
                      hx_post="/ui/jobs/clear", hx_target="#jobhistory", hx_swap="outerHTML"),
        cls="row",
    )
    return Div(header, body,
               P("Finished jobs (done/error) are kept for 30 days, then pruned on "
                 "startup — or clear them now. Queued/running/paused jobs are kept "
                 "and resume after a restart.", cls="muted"),
               id="jobhistory")


@rt("/jobs")
def jobs_history_page(sess):
    return page(
        Div(H2("Live jobs"), jobs_fragment(), cls="card"),
        Div(job_history_fragment(), cls="card"),
        sess=sess,
    )


@rt("/ui/jobs/clear", methods=["POST"])
def ui_jobs_clear(req, sess, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        store.delete_finished_jobs()
        jobs.manager.clear_finished()
    return job_history_fragment()


@rt("/ui/jobs/{job_id}/retry", methods=["POST"])
def ui_job_retry(req, sess, job_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        try:
            jobs.manager.retry(job_id)
        except (jobs.InsufficientSpace, jobs.Busy):
            pass
    return job_history_fragment()


@rt("/ui/archives", methods=["GET"])
def ui_archives():
    return archives_fragment()


@rt("/ui/summary", methods=["GET"])
def ui_summary():
    return summary_fragment()


@rt("/ui/check/{repo_id:path}", methods=["POST"])
def ui_check(req, sess, repo_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        try:
            jobs.check_update(repo_id)
        except KeyError:
            pass
    return archives_fragment()


@rt("/ui/check-all", methods=["POST"])
def ui_check_all(req, sess, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        for a in store.list_archives():
            try:
                jobs.check_update(a["repo_id"])
            except Exception:
                pass
    return archives_fragment()


@rt("/ui/delete/{repo_id:path}", methods=["POST"])
def ui_delete(req, sess, repo_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        jobs.delete_archive(repo_id)
    return archives_fragment()


# --- data stores ---------------------------------------------------------

def stores_fragment(notice: str | None = None):
    rows = []
    for s in store.list_stores():
        default_cell = (
            Span("default", cls="badge current") if s["is_default"]
            else action_button("Make default", cls="ghost",
                               hx_post=f"/ui/stores/{s['id']}/default", hx_target="#stores", hx_swap="outerHTML")
        )
        try:
            free = util.human_size(util.free_space(s["path"]))
        except Exception:
            free = "—"
        actions = [
            action_button("Import", busy="Importing…", cls="ghost",
                          hx_post=f"/ui/stores/{s['id']}/import", hx_target="#stores", hx_swap="outerHTML"),
        ]
        # A store can be deleted only when it's non-default and empty.
        if not s["is_default"] and not s["n_models"]:
            actions.append(action_button("Delete", cls="danger",
                                         hx_post=f"/ui/stores/{s['id']}/delete", hx_target="#stores", hx_swap="outerHTML",
                                         hx_confirm=f"Remove store '{s['name']}'? (files on disk are left untouched)"))
        rows.append(Tr(
            Td(s["name"]),
            Td(s["path"], cls="mono muted"),
            Td(f"{s['n_models']}", cls="muted"),
            Td(free, cls="muted"),
            Td(default_cell),
            Td(Div(*actions, cls="row")),
        ))
    table = Table(
        Thead(Tr(Th("Name"), Th("Path"), Th("Models"), Th("Free"), Th("Default"), Th(""))),
        Tbody(*rows),
    )
    add = Form(
        Input(type="text", name="name", placeholder="name"),
        Input(type="text", name="path", placeholder="/absolute/path"),
        action_button("Add store", busy="Adding…"),
        hx_post="/ui/stores/add", hx_target="#stores", hx_swap="outerHTML",
        cls="row",
    )
    head = [H2("Data stores")]
    if notice:
        head.append(P(notice, cls="muted"))
    return Div(*head, table, add,
               P("Import scans a store's folder and rebuilds the catalog from each "
                 "model's .hugger.json.", cls="muted"),
               id="stores")


@rt("/stores")
def stores_page(sess):
    return page(Div(stores_fragment(), cls="card"), sess=sess)


@rt("/ui/stores/add", methods=["POST"])
def ui_store_add(req, sess, name: str = "", path: str = "", csrf: str = ""):
    if _guard_csrf(req, sess, csrf) and name.strip() and path.strip():
        from pathlib import Path as _P
        p = str(_P(path).expanduser())
        try:
            util.check_writable(p)  # creates the dir and verifies it's writable
        except OSError as e:
            return stores_fragment(notice=f"⚠️ {path} is not writable: {e}")
        try:
            store.add_store(name.strip(), p)  # rejects paths overlapping another store
        except ValueError as e:
            return stores_fragment(notice=f"⚠️ {e}")
    return stores_fragment()


@rt("/ui/stores/{store_id}/import", methods=["POST"])
def ui_store_import(req, sess, store_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        try:
            n = jobs.import_store(store_id)
            return stores_fragment(notice=f"Imported {n} model(s).")
        except KeyError:
            pass
    return stores_fragment()


@rt("/ui/stores/{store_id}/default", methods=["POST"])
def ui_store_default(req, sess, store_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf):
        store.set_default_store(store_id)
    return stores_fragment()


@rt("/ui/stores/{store_id}/delete", methods=["POST"])
def ui_store_delete(req, sess, store_id: str, csrf: str = ""):
    if _guard_csrf(req, sess, csrf) and store.store_model_count(store_id) == 0:
        store.delete_store(store_id)
    return stores_fragment()


# --- settings ------------------------------------------------------------

@rt("/settings")
def settings(sess, msg: str = ""):
    note = P(msg, cls="muted") if msg else ""
    token_card = Div(
        H2("Extension API token"),
        P("Paste this into the hugger browser extension to authorize it. "
          "Keep it secret — it grants archive access.", cls="muted"),
        Div(Span(cfg.api_token, cls="mono"), cls="card", style="background:#fffdf6"),
        Form(Button("Rotate token", cls="danger"),
             method="post", action="/settings/rotate-token"),
        cls="card",
    )
    src = hub.hf_token_source()
    src_label = {
        "ui": "A token is set (saved here).",
        "env": "Using a token from the environment (HF_TOKEN).",
        "none": "No token set — only public models are accessible.",
    }[src]
    hf_card = Div(
        H2("HuggingFace token"),
        P("Needed to download gated or private models. ", Span(src_label, cls="muted")),
        Form(
            Input(type="password", name="token", placeholder="hf_… (leave blank and Clear to remove)"),
            Button("Save token"),
            method="post", action="/settings/hf-token",
        ),
        (Form(Button("Clear token", cls="danger"), method="post", action="/settings/hf-token/clear")
         if src == "ui" else ""),
        cls="card",
    )
    pw_card = Div(
        H2("Change password"),
        Form(
            Input(type="password", name="current", placeholder="current password"),
            Input(type="password", name="new", placeholder="new password"),
            Button("Update password"),
            method="post", action="/settings/password",
        ),
        cls="card",
    )
    info = Div(
        H2("Server"),
        P(f"Version {VERSION}", cls="muted"),
        P("Archive dir: ", Span(str(ARCHIVE_DIR), cls="mono")),
        P("HTTPS-only mode: " + ("on" if cfg.https_only else "off"), cls="muted"),
        cls="card",
    )
    return page(note, token_card, hf_card, pw_card, info, sess=sess)


@rt("/settings/hf-token", methods=["POST"])
def settings_hf_token(token: str = ""):
    hub.set_hf_token(token.strip() or None)
    msg = "HF+token+saved" if token.strip() else "HF+token+cleared"
    return RedirectResponse(f"/settings?msg={msg}", status_code=303)


@rt("/settings/hf-token/clear", methods=["POST"])
def settings_hf_token_clear():
    hub.set_hf_token(None)
    return RedirectResponse("/settings?msg=HF+token+cleared", status_code=303)


@rt("/settings/rotate-token", methods=["POST"])
def settings_rotate():
    auth.rotate_token()
    return RedirectResponse("/settings?msg=Token+rotated", status_code=303)


@rt("/settings/password", methods=["POST"])
def settings_password(current: str = "", new: str = ""):
    if not auth.verify_password(current):
        return RedirectResponse("/settings?msg=Current+password+incorrect", status_code=303)
    if len(new) < 6:
        return RedirectResponse("/settings?msg=New+password+too+short", status_code=303)
    auth.set_password(new)
    return RedirectResponse("/settings?msg=Password+updated", status_code=303)


# --- JSON API (extension; Bearer token via _before) ----------------------

@rt("/api/ping", methods=["GET"])
def api_ping():
    return JSONResponse({"ok": True, "version": VERSION})


@rt("/api/archive", methods=["POST"])
async def api_archive(req):
    body = {}
    try:
        body = await req.json()
    except Exception:
        form = await req.form()
        body = dict(form)
    repo_id = (body.get("repo_id") or "").strip()
    if not repo_id:
        return JSONResponse({"error": "repo_id required"}, status_code=400)
    revision = (body.get("revision") or "main").strip()
    store_id = (body.get("store_id") or "").strip() or None
    files = body.get("files") or None  # optional list of paths -> selective download
    if isinstance(files, str):
        files = [files]
    try:
        job = jobs.manager.start_download(repo_id, revision, store_id=store_id, selected=files)
    except jobs.InsufficientSpace as e:
        return JSONResponse({"error": str(e)}, status_code=507)
    return JSONResponse({"job_id": job.id, "repo_id": repo_id})


@rt("/api/files", methods=["GET"])
def api_files(req):
    """List a repo's files with sizes + whether each is already downloaded."""
    repo_id = (req.query_params.get("repo_id") or "").strip()
    revision = (req.query_params.get("revision") or "main").strip()
    if not repo_id:
        return JSONResponse({"error": "repo_id required"}, status_code=400)
    try:
        info = hub.repo_files(repo_id, revision)
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=502)
    statuses, _ = file_statuses(repo_id, info["files"])
    out = []
    for f in info["files"]:
        st = statuses[f["path"]]
        out.append({
            "path": f["path"], "size": f["size"],
            "downloaded": st == "downloaded",
            "downloading": st == "downloading",
        })
    return JSONResponse({"repo_id": repo_id, "sha": info["sha"], "files": out})


@rt("/api/verify/{repo_id:path}", methods=["GET"])
def api_verify(req):
    try:
        return JSONResponse(jobs.manager.verify(req.path_params["repo_id"]))
    except KeyError:
        return JSONResponse({"error": "not archived"}, status_code=404)
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=502)


@rt("/api/file-status", methods=["GET"])
def api_file_status(req):
    repo_id = (req.query_params.get("repo_id") or "").strip()
    path = (req.query_params.get("path") or "").strip()
    if not repo_id or not path:
        return JSONResponse({"error": "repo_id and path required"}, status_code=400)
    return JSONResponse(jobs.file_status(repo_id, path))


@rt("/api/stores/{store_id}/import", methods=["POST"])
def api_store_import(req):
    try:
        n = jobs.import_store(req.path_params["store_id"])
    except KeyError:
        return JSONResponse({"error": "store not found"}, status_code=404)
    return JSONResponse({"ok": True, "imported": n})


@rt("/api/status/{job_id}", methods=["GET"])
def api_status(job_id: str):
    job = jobs.manager.get(job_id)
    if not job:
        return JSONResponse({"error": "not found"}, status_code=404)
    return JSONResponse(job.as_dict())


@rt("/api/jobs/{job_id}/pause", methods=["POST"])
def api_job_pause(req):
    jobs.manager.pause(req.path_params["job_id"])
    return JSONResponse({"ok": True})


@rt("/api/jobs/{job_id}/resume", methods=["POST"])
def api_job_resume(req):
    jobs.manager.resume(req.path_params["job_id"])
    return JSONResponse({"ok": True})


@rt("/api/stores", methods=["GET"])
def api_stores():
    return JSONResponse({"stores": store.list_stores()})


@rt("/api/archives", methods=["GET"])
def api_archives():
    return JSONResponse({"archives": store.list_archives()})


@rt("/api/archive/{repo_id:path}", methods=["GET"])
def api_archive_status(req):
    """Whether a specific repo is archived — used by the extension to decide
    between offering Archive vs Remove/Update."""
    repo_id = req.path_params["repo_id"]
    rec = store.get_archive(repo_id)
    if not rec:
        return JSONResponse({"repo_id": repo_id, "archived": False})
    return JSONResponse({
        "repo_id": repo_id,
        "archived": True,
        "sha": rec["sha"],
        "size_bytes": rec["size_bytes"],
        "update_available": bool(rec["update_available"]),
    })


@rt("/api/archive/{repo_id:path}", methods=["DELETE"])
def api_archive_delete(req):
    repo_id = req.path_params["repo_id"]
    jobs.delete_archive(repo_id)
    return JSONResponse({"ok": True, "repo_id": repo_id})


# --- entrypoint ----------------------------------------------------------

def main() -> None:
    store.run_migrations()
    store.ensure_default_store(str(ARCHIVE_DIR))  # default store lives in ~/.hugger
    store.prune_jobs()  # drop finished jobs older than the retention window
    _bootstrap_password()
    jobs.manager.resume_pending()  # re-launch downloads/moves interrupted by a restart
    import uvicorn

    print(f"hugger {VERSION} → http://{cfg.host}:{cfg.port}")
    uvicorn.run(app, host=cfg.host, port=cfg.port)


if __name__ == "__main__":
    main()
