"""hugger — FastHTML app: SSR web UI + token-authenticated JSON API.

Hardened for internet exposure: argon2 password login, signed session cookies,
per-IP login throttle, CSRF tokens on state-changing UI routes, Bearer-token API
for the browser extension, security headers + TrustedHost, optional HSTS/CORS.
"""
from __future__ import annotations

import asyncio
import json
import os
import re
import secrets
from pathlib import Path
from urllib.parse import quote

from datastar_py import ServerSentEventGenerator as SSE
from datastar_py.fasthtml import DatastarResponse, read_signals
from fasthtml.common import *  # noqa: F403  (FT tags, fast_app, serve, Beforeware, RedirectResponse)
from starlette.datastructures import MutableHeaders
from starlette.middleware import Middleware
from starlette.middleware.cors import CORSMiddleware
from starlette.middleware.trustedhost import TrustedHostMiddleware
from starlette.responses import JSONResponse
from starlette.routing import Mount
from starlette.staticfiles import StaticFiles

_STATIC_DIR = Path(__file__).parent / "static"

from . import _live, auth, hub, jobs, metadata, store, util
from .config import ARCHIVE_DIR, cfg
from .hub import search_models

VERSION = "0.1.0"

# --- bootstrap secrets / password ----------------------------------------

def _bootstrap_password() -> None:
    """Ensure a password exists. Env HUGGER_PASSWORD sets/updates it; otherwise a
    random one is generated, printed once, and flagged so the user is forced to
    change it on first login."""
    env_pw = os.environ.get("HUGGER_PASSWORD")
    if env_pw:
        auth.set_password(env_pw, autogenerated=False)
        return
    if not auth.has_password():
        generated = secrets.token_urlsafe(12)
        auth.set_password(generated, autogenerated=True)
        banner = (
            "=" * 60
            + "\n hugger: no password set — generated an initial one:"
            + f"\n   PASSWORD: {generated}"
            + "\n   You'll be required to change it on first login.\n"
            + "=" * 60
        )
        print(banner, flush=True)


# --- helpers -------------------------------------------------------------

def human_size(n: int) -> str:
    f = float(n)
    for unit in ("B", "KB", "MB", "GB", "TB"):
        if f < 1024 or unit == "TB":
            return f"{f:.0f} {unit}" if unit == "B" else f"{f:.1f} {unit}"
        f /= 1024
    return f"{f:.1f} TB"


def human_rate(bytes_per_sec: float) -> str:
    return f"{human_size(bytes_per_sec)}/s" if bytes_per_sec > 0 else ""


def human_eta(seconds: int | None) -> str:
    """Compact remaining-time, e.g. '45s', '3m 20s', '1h 4m'."""
    if seconds is None or seconds < 0:
        return ""
    if seconds < 60:
        return f"{seconds}s"
    m, s = divmod(seconds, 60)
    if m < 60:
        return f"{m}m {s}s"
    h, m = divmod(m, 60)
    return f"{h}h {m}m"


async def _ds_csrf_ok(req, sess) -> bool:
    """CSRF check for Datastar actions: the token rides as the `csrf` signal
    (sent in the JSON body for POST, the `datastar` query for GET)."""
    signals = await read_signals(req) or {}
    return auth.csrf_ok(sess, signals.get("csrf"))


# Download icon: an arrow-down inside a circle (inline SVG, inherits text colour).
def dl_icon(size: int = 16):
    return NotStr(
        f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" '
        'aria-hidden="true" style="flex:none"><circle cx="12" cy="12" r="10"></circle>'
        '<path d="M12 8v8"></path><path d="m8 12 4 4 4-4"></path></svg>'
    )


# Reload icon: circular refresh arrows (check/update actions).
def reload_icon(size: int = 16):
    return NotStr(
        f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" '
        'aria-hidden="true" style="flex:none"><polyline points="23 4 23 10 17 10"></polyline>'
        '<polyline points="1 20 1 14 7 14"></polyline>'
        '<path d="M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15"></path></svg>'
    )


# Verify icon: a shield with a check (integrity hashing).
def verify_icon(size: int = 16):
    return NotStr(
        f'<svg width="{size}" height="{size}" viewBox="0 0 24 24" fill="none" '
        'stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" '
        'aria-hidden="true" style="flex:none"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z">'
        '</path><path d="m9 12 2 2 4-4"></path></svg>'
    )


def ds_button(label: str, action: str, *, indicator: str, busy: str | None = None,
              cls: str = "", icon=None, **kw):
    """Button that fires a Datastar action (e.g. "@post('/x')") with built-in busy
    feedback: a local indicator signal (underscore-prefixed → not sent to the
    backend) disables the button and toggles the busy styling/label while the
    request is in flight. `icon` (FT/SVG) is shown before the label. No per-button
    JS, no request-class wiring."""
    busy = busy or (label.rstrip(".… ") + "…")
    idle = (icon, label) if icon is not None else (label,)
    busyc = (icon, busy) if icon is not None else (busy,)
    return Button(
        Span(*idle, cls="idle"), Span(*busyc, cls="busy"), cls=cls,
        **{"data-on:click": action,
           "data-indicator": indicator,
           "data-attr:disabled": f"${indicator}",
           "data-class": '{"is-busy": $%s}' % indicator},
        **kw,
    )


def _sig(prefix: str, key: str) -> str:
    """A DOM-safe, per-element local indicator signal name. Underscore-prefixed so
    Datastar treats it as local (never sent to the backend)."""
    return "_" + prefix + re.sub(r"[^0-9a-zA-Z]", "", key)


# status -> pill colour class (JobStatus design component palette)
_PILL = {
    "current": "ok", "done": "ok", "unchanged": "ok", "downloaded": "ok",
    "update": "warn", "update available": "warn", "paused": "warn", "queued": "warn",
    "missing": "err", "error": "err", "changed": "err", "bad": "err",
    "running": "info", "downloading": "info",
}


def status_pill(label: str):
    """A coloured status pill (with a dot) for a job/file status string."""
    return Span(label, cls=f"badge {_PILL.get(label.lower(), '')}".rstrip())


def job_kind(job_type: str):
    """Inline job-kind indicator: icon + label per job type."""
    if job_type == "move":
        return Span("⇄ move", cls="muted kind")
    if job_type == "verify":
        return Span(verify_icon(14), "verify", cls="muted kind")
    return Span(dl_icon(14), "download", cls="muted kind")


# --- reusable Datastar components ----------------------------------------

def live_panel(body, *, wrapper_id: str, stream_url: str):
    """A panel kept live by a Datastar SSE stream. data-init opens the stream once
    when the wrapper is initialized (the wrapper itself is never patched); the
    stream morphs `body`, which must carry its own id. (`data-on:load` won't work —
    the `load` DOM event never fires on a div.)"""
    return Div(body, id=wrapper_id, **{"data-init": f"@get('{stream_url}')"})


def sse_stream(render, *, keepalive: float = 20.0):
    """DatastarResponse for a long-lived, event-driven stream. It morphs
    `render()`'s element whenever the app signals a change (`_live.bump()`), not on
    a timer — idle state means no wakeups and no traffic. It re-renders on wake and
    pushes a patch only if the HTML actually changed. `keepalive` is just a slow
    heartbeat (proxy keep-alive / belt-and-braces); `render` returns an FT element
    with a stable id."""
    async def gen():
        last = None
        seen = _live.version()
        try:
            while not _live.is_shutting_down():
                html = to_xml(render())
                if html != last:
                    yield SSE.patch_elements(html)
                    last = html
                seen = await _live.wait(seen, keepalive)
        except asyncio.CancelledError:
            return  # client navigated away / server shutting down — stop cleanly
    return DatastarResponse(gen())


def patch(*elements):
    """DatastarResponse that morphs one or more FT elements once (in place)."""
    return DatastarResponse([SSE.patch_elements(to_xml(e)) for e in elements])


# --- interactive UI helpers ----------------------------------------------

def action_button(label: str, *, busy: str | None = None, **kw):
    """Submit button for the plain full-page forms (login/settings). busy.js adds
    the `is-busy` class on submit; CSS then recolors and swaps to the busy label
    (e.g. "Save" -> "Saving…") until the page navigates. Datastar buttons use
    ds_button instead."""
    if busy is None:
        busy = label.rstrip(".… ") + "…"
    return Button(Span(label, cls="idle"), Span(busy, cls="busy"), **kw)


async def _ds(req) -> dict:
    """All Datastar signals sent with the request (JSON body / `datastar` query)."""
    return await read_signals(req) or {}


def modal(title: str, *content):
    """Overlay wrapper; rendered into the page-level #modal container."""
    return Div(
        Div(
            Div(H3(title),
                Button("✕", cls="modal-close", **{"data-on:click": "@get('/ui/close')"}),
                cls="modal-head"),
            *content,
            cls="modal-card",
        ),
        cls="modal-overlay",
    )


def show_modal(overlay):
    """SSE response that shows a modal (morphs #modal to hold the overlay)."""
    return patch(Div(overlay, id="modal"))


def modal_close():
    """SSE response that dismisses the modal (morphs #modal empty)."""
    return patch(Div(id="modal"))


def file_list(files: list[dict], *, submit_buttons: list, signals: dict | None = None,
              preselect=None, statuses: dict | None = None, removable_repo: str | None = None,
              disabled=None):
    """Reusable Datastar file picker. Checkboxes bind to a `files` array signal
    (its initial value = the preselected, non-disabled paths); `submit_buttons`
    are Datastar actions that read it. `signals` seeds extra picker signals (repo,
    store, mode…). `disabled` paths can't be selected; `removable_repo` adds a
    per-file Remove action."""
    preselect = preselect if preselect is not None else {f["path"] for f in files}
    disabled = disabled or set()
    selected = [f["path"] for f in files if f["path"] in preselect and f["path"] not in disabled]
    seed = {"files": selected, "mode": "all", **(signals or {})}
    head = [Th("File"), Th("Size", cls="r")]
    if statuses is not None:
        head.append(Th("Status"))
    if removable_repo:
        head.append(Th("", cls="r"))
    rows = []
    for f in files:
        is_disabled = f["path"] in disabled
        cells = [
            # checkbox + filename together in the File cell (label), per the design
            Td(Label(
                Input(type="checkbox", value=f["path"], disabled=is_disabled,
                      **{"data-bind": "files"}),
                Span(f["path"], cls="mono wrap"),
                cls="fcheck",
            )),
            Td(human_size(f["size"]), cls="muted r"),
        ]
        status = statuses.get(f["path"]) if statuses is not None else None
        if statuses is not None:
            cells.append(Td(status_pill(status)))
        if removable_repo:
            rm = (ds_button("Remove", f"@post('/ui/file-remove/{removable_repo}?path={quote(f['path'])}')",
                            indicator=_sig("rm", f["path"]), cls="danger")
                  if status in ("downloaded", "bad") else "")
            cells.append(Td(rm))
        rows.append(Tr(*cells))
    return Div(
        Div(Table(Thead(Tr(*head)), Tbody(*rows)), cls="filelist"),
        Div(*submit_buttons, cls="row"),
        **{"data-signals": json.dumps(seed)},
    )


def file_statuses(repo_id: str, files: list[dict]):
    """Per-file status (downloaded / downloading / missing) + the set of paths
    that are currently downloading (and so can't be selected)."""
    rec = store.get_archive(repo_id)
    downloading = jobs.manager.active_download_files(repo_id)
    bad = set(metadata.read_bad(rec["path"]).get("files", [])) if rec else set()
    statuses = {}
    for f in files:
        if f["path"] in downloading:
            statuses[f["path"]] = "downloading"
        elif f["path"] in bad:
            statuses[f["path"]] = "bad"  # failed verification
        elif rec and metadata.file_downloaded(rec["path"], f["path"], f["size"]):
            statuses[f["path"]] = "downloaded"
        else:
            statuses[f["path"]] = "missing"
    locked = {p for p, s in statuses.items() if s == "downloading"}
    return statuses, locked


# --- security middleware -------------------------------------------------

# All scripts are self-hosted from /static (no CDN, no inline script), so
# script-src is just 'self' plus 'unsafe-eval' — which Datastar needs to evaluate
# data-* expressions via the Function constructor. SSE actions use same-origin
# fetch (connect-src).
_CSP = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-eval'; "
    "style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'"
)


class SecurityHeaders:
    """Pure-ASGI security-header middleware. Pure ASGI (not BaseHTTPMiddleware) so
    it doesn't wrap streaming responses in a memory stream — that buffering hurts
    SSE flushing and throws a CancelledError traceback when long-lived streams are
    cancelled on shutdown."""

    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        if scope["type"] != "http":
            return await self.app(scope, receive, send)
        if scope["method"] in ("GET", "HEAD"):
            scope = dict(scope, headers=[h for h in scope["headers"] if h[0] != b"content-type"])

        async def send_with_headers(message):
            if message["type"] == "http.response.start":
                h = MutableHeaders(scope=message)
                h["X-Content-Type-Options"] = "nosniff"
                h["X-Frame-Options"] = "DENY"
                h["Referrer-Policy"] = "no-referrer"
                h["Content-Security-Policy"] = _CSP
                if cfg.https_only:
                    h["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"
            await send(message)

        await self.app(scope, receive, send_with_headers)


def _middleware() -> list:
    mw = [Middleware(TrustedHostMiddleware, allowed_hosts=cfg.allowed_hosts)]
    if cfg.allowed_origins:
        mw.append(
            Middleware(
                CORSMiddleware,
                allow_origins=cfg.allowed_origins,
                allow_methods=["GET", "POST", "DELETE"],
                allow_headers=["authorization", "x-hugger-token", "content-type"],
            )
        )
    mw.append(Middleware(SecurityHeaders))
    return mw


# --- auth gate -----------------------------------------------------------

def _before(req, sess):
    path = req.url.path
    if path.startswith("/api/"):
        if not auth.verify_token(auth.bearer_from_request(req)):
            return JSONResponse({"error": "unauthorized"}, status_code=401)
        return  # token ok -> allow
    if not sess.get("auth"):
        return RedirectResponse("/login", status_code=303)
    # Force an autogenerated password to be changed before anything else.
    if auth.must_change_password() and path not in ("/change-password", "/logout"):
        return RedirectResponse("/change-password", status_code=303)


beforeware = Beforeware(
    _before,
    skip=[r"/favicon\.ico", r"/static/.*", r".*\.css", r".*\.js", "/login"],
)


# Head tags, all self-hosted (no CDN, tight CSP). Datastar drives interactivity;
# busy.js only adds busy feedback to the plain full-page forms (login/settings).
HEAD = (
    Meta(charset="utf-8"),
    Meta(name="viewport", content="width=device-width, initial-scale=1"),
    Link(rel="stylesheet", href="/static/fonts.css"),  # self-hosted Baloo 2 / Nunito Sans / JetBrains Mono
    Link(rel="stylesheet", href="/static/tailwind.css"),  # built by the Tailwind CLI (scripts/build-css.sh)
    Script(type="module", src="/static/datastar.js"),
    Script(src="/static/busy.js"),
)

app, rt = fast_app(
    secret_key=cfg.secret_key,
    before=beforeware,
    middleware=_middleware(),
    pico=False,
    default_hdrs=False,  # no htmx / fasthtml-js / surreal / css-scope-inline
    hdrs=HEAD,
    # On graceful shutdown, mark in-flight jobs queued (not failed) so they resume.
    on_shutdown=[jobs.manager.shutdown],
)

# Serve the vendored runtime from the package's static dir. Insert ahead of
# FastHTML's built-in catch-all static route (which serves from cwd) so /static
# resolves here regardless of the working directory.
app.routes.insert(0, Mount("/static", StaticFiles(directory=str(_STATIC_DIR)), name="static"))


# --- shared fragments ----------------------------------------------------

def search_results(models: list[dict], query: str = ""):
    """Search results rendered as a modal; each row opens the file picker modal."""
    if not models:
        return modal(f"Search · {query}".rstrip(" ·"), P("No results.", cls="muted"))
    rows = []
    for m in models:
        rows.append(
            Tr(
                Td(A(m["id"], href=f"https://huggingface.co/{m['id']}", target="_blank", cls="link mono")),
                Td(f"{m['downloads']:,}", cls="muted"),
                Td(f"♥ {m['likes']}", cls="muted"),
                Td(
                    ds_button("Archive…", f"$repo = '{m['id']}'; @get('/ui/files')",
                              indicator=_sig("a", m["id"]), busy="Opening…", icon=dl_icon()),
                ),
            )
        )
    return modal(
        f"Search · {query}".rstrip(" ·"),
        Div(Table(Thead(Tr(Th("Model"), Th("Downloads"), Th("Likes"), Th())), Tbody(*rows)), cls="filelist"),
    )


def _job_verb(j) -> str:
    """Present-tense action, for '<verb> failed'."""
    return {"move": "move", "verify": "verify"}.get(j.type, "download")


def _job_done_word(j) -> str:
    """Past tense, for a finished job."""
    return {"move": "moved", "verify": "verified"}.get(j.type, "downloaded")


def jobs_body(notice: str | None = None):
    """Inner content of the jobs panel (id #jobs-body). The Datastar stream morphs
    this in place every second; one-shot htmx actions retarget it too. Pause/Resume
    are Datastar actions — morph never destroys them, so they can't be clobbered."""
    active = jobs.manager.active()
    finished = [j for j in jobs.manager.recent() if j.status in ("done", "error")]
    items = []
    for j in active:
        ind = _sig("b", j.id)
        controls = []
        if j.status == "paused":
            controls.append(ds_button("Resume", f"@post('/ui/jobs/{j.id}/resume')",
                                       indicator=ind, cls="ghost"))
            if j.type == "download":  # only paused downloads can re-pick files
                controls.append(ds_button("Edit files", f"@get('/ui/jobs/{j.id}/files')",
                                          indicator=_sig("e", j.id), busy="Opening…"))
            state = status_pill("paused")
        elif j.status == "queued":
            # Queued behind another job: let the user jump the queue or pause it.
            controls.append(ds_button("Run now", f"@post('/ui/jobs/{j.id}/run-now')",
                                       indicator=_sig("rn", j.id), busy="Starting…"))
            controls.append(ds_button("Pause", f"@post('/ui/jobs/{j.id}/pause')",
                                       indicator=ind, cls="ghost"))
            state = status_pill("queued")
        else:
            controls.append(ds_button("Pause", f"@post('/ui/jobs/{j.id}/pause')",
                                       indicator=ind, cls="ghost"))
            state = status_pill(j.status)
        # progress / rate / ETA / stall line
        stats = [Span(f"{human_size(j.done_bytes)} / {human_size(j.total_bytes)}", cls="muted")]
        if j.status == "running" and j.rate > 0:
            stats.append(Span(f"· {human_rate(j.rate)}", cls="muted"))
            if j.eta is not None:
                stats.append(Span(f"· ETA {human_eta(j.eta)}", cls="muted"))
        if j.stalls:
            stats.append(Span(f"· restarted {j.stalls}×", cls="badge warn",
                              title="auto-restarted after stalling"))
        items.append(
            Div(
                Div(job_kind(j.type), Span(j.repo_id, cls="mono"), state, cls="row"),
                Progress(value=str(j.done_bytes), max=str(max(j.total_bytes, 1))),
                Div(*stats, *controls, cls="row"),
                cls="job", id=f"job-{ind}",
            )
        )
    for j in finished:
        if j.status == "error":
            items.append(Div(Span(j.repo_id, cls="mono"), Span(f" {_job_verb(j)} failed: ", cls="err"), Span(j.error or "", cls="err"), cls="job"))
        else:
            items.append(Div(Span("✓ ", cls=""), Span(j.repo_id, cls="mono"), Span(f" {_job_done_word(j)}", cls="muted"), cls="job"))
    inner = items or [P("No active jobs.", cls="muted")]
    if jobs.MAX_ACTIVE == 1 and sum(1 for j in active if j.status in ("queued", "running")) > 1:
        inner.append(P("ℹ︎ One job transfers at a time; the rest wait in the queue. "
                       "Use “Run now” to jump the queue.", cls="muted"))
    if notice:
        inner = [P(notice, cls="err"), *inner]
    return Div(*inner, id="jobs-body")


def jobs_panel(notice: str | None = None):
    """Jobs panel: a live SSE-streamed panel keeping #jobs-body current (no poll)."""
    return live_panel(jobs_body(notice), wrapper_id="jobs", stream_url="/ui/jobs")


def _short(sha: str | None) -> str:
    return (sha or "")[:8]


def _move_control(repo_id: str, current_store_id: str | None, stores: list[dict]):
    others = [s for s in stores if s["id"] != current_store_id]
    if not others:
        # Nowhere to move to yet — point the user at adding a store.
        return A("Move…", href="/stores", cls="link muted", title="Add another store to move into")
    return Div(
        Select(*[Option(s["name"], value=s["id"]) for s in others], **{"data-bind": "movestore"}),
        ds_button("Move", f"@post('/ui/move/{repo_id}')", indicator=_sig("mv", repo_id), cls="ghost"),
        cls="row", **{"data-signals": json.dumps({"movestore": others[0]["id"]})},
    )


def archives_body():
    rows = []
    for a in store.list_archives():
        rid = a["repo_id"]
        badge = (
            Span("update available", cls="badge update")
            if a["update_available"]
            else Span("current", cls="badge current")
        )
        rows.append(
            Tr(
                Td(A(rid, href=f"https://huggingface.co/{rid}", target="_blank", cls="link mono")),
                Td(a.get("store_name") or "—", cls="muted"),
                Td(human_size(a["size_bytes"]), cls="muted"),
                Td(_short(a["sha"]), cls="mono muted"),
                Td(badge),
                Td(
                    Div(
                        A("Manage", href=f"/manage/{rid}", cls="btn ghost"),
                        (ds_button("Update…", f"@get('/ui/update/{rid}')",
                                   indicator=_sig("u", rid), busy="Checking…")
                         if a["update_available"] else
                         ds_button("Check", f"@post('/ui/check/{rid}')",
                                   indicator=_sig("c", rid), cls="ghost")),
                        ds_button("Delete", f"confirm('Delete archive {rid} from disk?') && @post('/ui/delete/{rid}')",
                                  indicator=_sig("d", rid), cls="danger"),
                        cls="actions",
                    )
                ),
            )
        )
    body = (
        Table(
            Thead(Tr(Th("Model"), Th("Store"), Th("Size"), Th("Commit"), Th("Status"), Th("Actions", cls="r"))),
            Tbody(*rows),
        )
        if rows
        else P("Nothing archived yet. Search above or use the browser extension.", cls="muted")
    )
    header = Div(
        H2("Archived models"),
        ds_button("Check all for updates", "@post('/ui/check-all')",
                  indicator="_checkall", busy="Checking…", cls="ghost", icon=reload_icon()),
        cls="section-head",
    )
    return Div(header, body, id="archives-body")


def archives_panel():
    """Archives list, kept live by an SSE stream (morphs #archives-body)."""
    return live_panel(archives_body(), wrapper_id="archives", stream_url="/ui/archives")


def summary_fragment():
    """Compact recent-activity view for the dashboard (full table lives at /archives)."""
    archives = store.list_archives()
    total = len(archives)
    size = sum(a["size_bytes"] for a in archives)
    updates = sum(1 for a in archives if a["update_available"])

    stats = Div(
        Span(f"{total}", cls="stat-num"), Span(" archived", cls="muted"),
        Span(" · ", cls="muted"), Span(human_size(size), cls="stat-num"),
        Span(" on disk", cls="muted"),
        *([Span(" · ", cls="muted"), Span(f"{updates}", cls="stat-num"),
           Span(" update(s) available", cls="muted")] if updates else []),
        cls="row",
    )
    if archives:
        recent = [
            Li(
                A(a["repo_id"], href=f"https://huggingface.co/{a['repo_id']}",
                  target="_blank", cls="link mono"),
                Span(f" · {human_size(a['size_bytes'])} ", cls="muted"),
                (status_pill("update available") if a["update_available"] else ""),
                cls="row",
            )
            for a in archives[:5]
        ]
        recent_list = Ul(*recent)
    else:
        recent_list = P("Nothing archived yet. Search above or use the browser extension.", cls="muted")

    return Div(
        H2("Recent activity"),
        stats,
        recent_list,
        A("View all archives →", href="/archives", cls="link"),
        id="summary-body",
    )


def summary_panel():
    """Dashboard recent-activity, kept live by an SSE stream (morphs #summary-body)."""
    return live_panel(summary_fragment(), wrapper_id="summary", stream_url="/ui/summary")


_NAV = [("Home", "/", "home"), ("Archives", "/archives", "archives"),
        ("Jobs", "/jobs", "jobs"), ("Stores", "/stores", "stores"),
        ("Settings", "/settings", "settings"), ("Logout", "/logout", None)]


def page(*content, sess=None, active=None):
    csrf = auth.csrf_token(sess) if sess is not None else ""
    links = []
    for label, href, key in _NAV:
        kw = {"aria-current": "page", "cls": "active"} if key and key == active else {}
        links.append(A(label, href=href, **kw))
    return Title("hugger"), Div(
        Header(Div(
            H1("🤗 hugger"),
            Nav(*links, **{"aria-label": "Primary"}),
            cls="bar",
        )),
        Main(*content),
        Div(id="modal"),  # action modals (file lists) render here
        id="app",
        # CSRF for Datastar actions rides as the `csrf` signal (JSON body for POST,
        # `datastar` query for GET).
        **{"data-signals": json.dumps({"csrf": csrf})},
    )


@rt("/ui/close", methods=["GET"])
def ui_close():
    return modal_close()


# --- pages ---------------------------------------------------------------

def store_selector():
    """Target-store control for new downloads, bound to the `store` signal."""
    stores = store.list_stores()
    if len(stores) <= 1:
        sid = stores[0]["id"] if stores else ""
        return Div(**{"data-signals": json.dumps({"store": sid})})
    default = next((s for s in stores if s["is_default"]), stores[0])
    return Div(
        Span("Target store: ", cls="muted"),
        Select(
            *[Option(s["name"], value=s["id"]) for s in stores],
            **{"data-bind": "store"},
        ),
        cls="row", **{"data-signals": json.dumps({"store": default["id"]})},
    )


@rt("/")
def index(sess):
    search = Div(
        H2("Find a model"),
        Div(
            Input(type="text", placeholder="e.g. llama, bert, whisper…", **{"data-bind": "q"}),
            ds_button("Search", "@post('/ui/search')", indicator="_search", busy="Searching…"),
            cls="row",
        ),
        cls="card",
    )
    manual = Div(
        Input(type="text", placeholder="org/model — archive by id", cls="mono", **{"data-bind": "repo"}),
        ds_button("Archive…", "@get('/ui/files')", indicator="_arch", busy="Opening…", icon=dl_icon()),
        cls="row mb",
    )
    downloads = Div(
        H2("Downloads"),
        Div(store_selector(), cls="mb-sm"),
        manual,
        Div(jobs_panel(), cls="divider-top"),
        cls="card",
    )
    blocks = []
    if hub.hf_token_source() == "none":
        blocks.append(Div(
            Span("⚠️", cls="notice-icon", **{"aria-hidden": "true"}),
            P("No HuggingFace token set. ",
              A("Add one in Settings", href="/settings"),
              " for faster downloads and to avoid rate limits."),
            cls="notice",
        ))
    blocks += [search, downloads, Div(summary_panel(), cls="card")]
    return page(*blocks, sess=sess, active="home")


@rt("/archives")
def archives_page(sess):
    # Include the jobs panel so Move actions (which swap #jobs) have a target and
    # their progress is visible right here.
    return page(
        Div(archives_panel(), cls="card"),
        Div(H2("Jobs", cls="head-line"), jobs_panel(), cls="card"),
        sess=sess, active="archives",
    )


@rt("/login", methods=["GET"])
def login_form(req, error: str = ""):
    msg = P(error, cls="err") if error else ""
    return Title("hugger · login"), Div(
        Header(Div(H1("🤗 hugger"), cls="bar")),
        Main(
            Div(
                H2("Sign in"),
                msg,
                Form(
                    Input(type="password", name="password", placeholder="password", autofocus=True),
                    action_button("Sign in", busy="Signing in…"),
                    method="post", action="/login", cls="row",
                ),
                cls="card",
            )
        ),
        id="app",
    )


@rt("/login", methods=["POST"])
def login(req, sess, password: str = ""):
    ip = req.client.host if req.client else "?"
    locked = auth.is_locked(ip)
    if locked:
        return RedirectResponse(f"/login?error=Too+many+attempts.+Try+again+in+{locked}s", status_code=303)
    if auth.verify_password(password):
        auth.record_success(ip)
        sess["auth"] = True
        auth.csrf_token(sess)  # mint a CSRF token for this session
        dest = "/change-password" if auth.must_change_password() else "/"
        return RedirectResponse(dest, status_code=303)
    auth.record_failure(ip)
    return RedirectResponse("/login?error=Invalid+password", status_code=303)


@rt("/change-password", methods=["GET"])
def change_password_form(sess, error: str = ""):
    forced = auth.must_change_password()
    msg = P(error, cls="err") if error else ""
    note = (
        P("Your password was generated automatically — choose a new one to continue.", cls="muted")
        if forced else ""
    )
    return Title("hugger · change password"), Div(
        Header(Div(H1("🤗 hugger"), cls="bar")),
        Main(
            Div(
                H2("Set a new password"),
                note, msg,
                Form(
                    Input(type="password", name="new", placeholder="new password", autofocus=True),
                    Input(type="password", name="confirm", placeholder="confirm new password"),
                    action_button("Save password", busy="Saving…"),
                    method="post", action="/change-password", cls="row",
                ),
                cls="card",
            )
        ),
        id="app",
    )


@rt("/change-password", methods=["POST"])
def change_password(sess, new: str = "", confirm: str = ""):
    if len(new) < 6:
        return RedirectResponse("/change-password?error=Password+too+short+(min+6)", status_code=303)
    if new != confirm:
        return RedirectResponse("/change-password?error=Passwords+do+not+match", status_code=303)
    auth.set_password(new, autogenerated=False)  # clears the must-change flag
    return RedirectResponse("/", status_code=303)


@rt("/logout")
def logout(sess):
    sess.clear()
    return RedirectResponse("/login", status_code=303)


@rt("/ui/search", methods=["POST"])
async def ui_search(req, sess):
    s = await _ds(req)
    if not auth.csrf_ok(sess, s.get("csrf")):
        return show_modal(modal("Search", P("Session expired, reload the page.", cls="err")))
    q = (s.get("q") or "").strip()
    return show_modal(search_results(search_models(q), query=q))


def _archive_modal(repo_id: str, store_id: str, notice: str | None = None):
    """The Archive file-picker modal (shows total size + an optional error)."""
    try:
        info = hub.repo_files(repo_id)
    except Exception as e:
        return modal("Archive", P(f"Could not list files for {repo_id}: {e}", cls="err"))
    statuses, locked = file_statuses(repo_id, info["files"])
    total = sum(f["size"] for f in info["files"])
    head = [P(notice, cls="err")] if notice else []
    head.append(P(f"Total {human_size(total)} · {len(info['files'])} files", cls="muted"))
    form = file_list(
        info["files"], statuses=statuses, disabled=locked,
        signals={"repo": repo_id, "store": store_id or ""},
        submit_buttons=[
            ds_button("Download all", "$mode='all'; @post('/ui/archive')", indicator="_dlall", icon=dl_icon()),
            ds_button("Download selected", "$mode='selected'; @post('/ui/archive')",
                      indicator="_dlsel", cls="ghost", icon=dl_icon()),
        ],
    )
    return modal(f"Archive {repo_id}", *head, form)


@rt("/ui/files", methods=["GET"])
async def ui_files(req, sess):
    s = await _ds(req)
    repo_id = (s.get("repo") or "").strip()
    if not repo_id:
        return modal_close()
    return show_modal(_archive_modal(repo_id, (s.get("store") or "").strip()))


@rt("/ui/archive", methods=["POST"])
async def ui_archive(req, sess):
    s = await _ds(req)
    if not auth.csrf_ok(sess, s.get("csrf")):
        return show_modal(modal("Archive", P("Session expired, reload the page.", cls="err")))
    repo_id = (s.get("repo") or "").strip()
    store_id = (s.get("store") or "").strip()
    selected = None if (s.get("mode") or "all") == "all" else list(s.get("files") or [])
    if repo_id:
        try:
            jobs.manager.start_download(repo_id, store_id=store_id or None, selected=selected)
        except (jobs.InsufficientSpace, jobs.Busy) as e:
            # Keep the picker open and show the error there.
            return show_modal(_archive_modal(repo_id, store_id, notice=f"⚠️ {e}"))
        except Exception as e:
            return show_modal(_archive_modal(repo_id, store_id, notice=f"⚠️ {type(e).__name__}: {e}"))
    return modal_close()


@rt("/ui/move/{repo_id:path}", methods=["POST"])
async def ui_move(req, sess, repo_id: str):
    s = await _ds(req)
    notice = None
    if auth.csrf_ok(sess, s.get("csrf")) and s.get("movestore"):
        try:
            jobs.manager.start_move(repo_id, s["movestore"])
        except (jobs.InsufficientSpace, jobs.Busy) as e:
            notice = f"⚠️ {e}"
        except KeyError:
            pass
    return patch(jobs_body(notice))


@rt("/ui/jobs/{job_id}/pause", methods=["POST"])
async def ui_job_pause(req, sess, job_id: str):
    if await _ds_csrf_ok(req, sess):
        jobs.manager.pause(job_id)
    return patch(jobs_body())


@rt("/ui/jobs/{job_id}/resume", methods=["POST"])
async def ui_job_resume(req, sess, job_id: str):
    if await _ds_csrf_ok(req, sess):
        jobs.manager.resume(job_id)
    return patch(jobs_body())


@rt("/ui/jobs/{job_id}/run-now", methods=["POST"])
async def ui_job_run_now(req, sess, job_id: str):
    if await _ds_csrf_ok(req, sess):
        jobs.manager.run_now(job_id)
    return patch(jobs_body())


@rt("/ui/jobs/{job_id}/files", methods=["GET"])
def ui_job_files(req, sess, job_id: str):
    job = jobs.manager.get(job_id)
    if not job or job.type != "download":
        return modal_close()
    try:
        info = hub.repo_files(job.repo_id, job.revision)
    except Exception as e:
        return show_modal(modal("Edit files", P(f"Could not list files: {e}", cls="err")))
    st = store.get_store(job.store_id)
    meta = metadata.read(jobs.store_repo_path(st["path"], job.repo_id)) if st else None
    selected = set(meta["selected"]) if meta else {f["path"] for f in info["files"]}
    form = file_list(
        info["files"], preselect=selected,
        submit_buttons=[ds_button("Save selection", f"@post('/ui/jobs/{job_id}/files')",
                                  indicator="_savesel")],
    )
    return show_modal(modal(f"Files for paused download · {job.repo_id}", form))


@rt("/ui/jobs/{job_id}/files", methods=["POST"])
async def ui_job_files_save(req, sess, job_id: str):
    s = await _ds(req)
    if auth.csrf_ok(sess, s.get("csrf")):
        jobs.manager.update_selected(job_id, list(s.get("files") or []))
    return modal_close()


def manage_list_fragment(repo_id: str):
    """The reusable file list for the manage page (download missing / remove)."""
    rec = store.get_archive(repo_id)
    if not rec:
        return Div(P("Not archived.", cls="muted"), id="managelist")
    try:
        info = hub.repo_files(repo_id, rec["revision"])
    except Exception as e:
        return Div(P(f"Could not list files: {e}", cls="err"), id="managelist")
    statuses, locked = file_statuses(repo_id, info["files"])
    preselect = {p for p, s in statuses.items() if s == "missing"}  # default: fetch missing
    form = file_list(
        info["files"], statuses=statuses,
        preselect=preselect, removable_repo=repo_id, disabled=locked,
        submit_buttons=[ds_button("Download selected", f"@post('/ui/manage/{repo_id}')",
                                  indicator="_mgdl", icon=dl_icon())],
    )
    return Div(form, id="managelist")


@rt("/manage/{repo_id:path}", methods=["GET"])
def manage_page(req, sess, repo_id: str):
    rec = store.get_archive(repo_id)
    if not rec:
        return page(Div(P("Not archived.", cls="muted"), cls="card"), sess=sess, active="archives")
    move = _move_control(repo_id, rec.get("store_id"), store.list_stores())
    crumbs = Nav(
        A("Archives", href="/archives", cls="link"),
        Span("/", cls="crumb-sep", aria_hidden="true"),
        Span(repo_id, cls="mono", aria_current="page"),
        cls="breadcrumb",
    )
    info = Div(
        H2(f"Manage {repo_id}"),
        P("Store: ", Span(rec.get("store_name") or "—", cls="mono"),
          " · ", Span(f"{rec['n_downloaded']}/{rec['n_files']} files", cls="muted"),
          " · ", Span(human_size(rec["size_bytes"]), cls="muted")),
        Div(Span("Move to another store: ", cls="muted"), move,
            ds_button("Verify", f"@post('/ui/verify/{repo_id}')", indicator=_sig("vf", repo_id),
                      busy="Verifying…", cls="ghost", icon=verify_icon()),
            cls="row"),
        cls="card",
    )
    bad = metadata.read_bad(rec["path"]).get("files", [])
    parts = [crumbs, info]
    if bad:
        parts.append(_bad_files_notice(repo_id, bad))
    parts += [
        Div(H2("Files", style="font-size:20px;margin-bottom:8px"), manage_list_fragment(repo_id), cls="card"),
        Div(H2("Jobs", cls="head-line"), jobs_panel(), cls="card"),
    ]
    return page(*parts, sess=sess, active="archives")


def _bad_files_notice(repo_id: str, bad: list[str]):
    """Warning card: files that failed verification + a one-click re-download
    (deletes them and resumes the download so only those are re-fetched)."""
    shown = ", ".join(bad[:6]) + (f" … (+{len(bad) - 6} more)" if len(bad) > 6 else "")
    return Div(
        Span("⚠️", cls="notice-icon", **{"aria-hidden": "true"}),
        Div(
            P(Strong(f"{len(bad)} file(s) failed verification"),
              " — the on-disk bytes don't match the expected hash."),
            P(Span(shown, cls="mono wrap"), cls="muted mb-sm"),
            ds_button(f"Re-download {len(bad)} bad file(s)", f"@post('/ui/redownload-bad/{repo_id}')",
                      indicator=_sig("rb", repo_id), busy="Starting…", icon=dl_icon()),
            cls="grow",
        ),
        cls="notice",
    )


@rt("/ui/manage/{repo_id:path}", methods=["POST"])
async def ui_manage_download(req, sess, repo_id: str):
    s = await _ds(req)
    if auth.csrf_ok(sess, s.get("csrf")):
        files = list(s.get("files") or [])
        rec = store.get_archive(repo_id)
        if files and rec:
            try:
                jobs.manager.start_download(repo_id, rec["revision"], store_id=rec["store_id"], selected=files)
            except (jobs.InsufficientSpace, jobs.Busy):
                pass  # the jobs stream surfaces failures; managelist just refreshes
    return patch(manage_list_fragment(repo_id))


@rt("/ui/file-remove/{repo_id:path}", methods=["POST"])
async def ui_file_remove(req, sess, repo_id: str):
    s = await _ds(req)
    if auth.csrf_ok(sess, s.get("csrf")):
        path = req.query_params.get("path")
        if path:
            jobs.manager.remove_file(repo_id, path)
    return patch(manage_list_fragment(repo_id))


@rt("/ui/verify/{repo_id:path}", methods=["POST"])
async def ui_verify(req, sess, repo_id: str):
    if await _ds_csrf_ok(req, sess):
        try:
            jobs.manager.start_verify(repo_id)
        except KeyError:
            pass
    return patch(jobs_body())


@rt("/ui/redownload-bad/{repo_id:path}", methods=["POST"])
async def ui_redownload_bad(req, sess, repo_id: str):
    if await _ds_csrf_ok(req, sess):
        try:
            jobs.manager.redownload_bad(repo_id)
        except (jobs.InsufficientSpace, jobs.Busy, KeyError):
            pass
    return patch(jobs_body())


def _update_modal(repo_id: str, notice: str | None = None):
    try:
        v = jobs.manager.verify(repo_id)
    except KeyError:
        return modal("Update", P("Not archived.", cls="muted"))
    except Exception as e:
        return modal("Update", P(f"Verify failed: {e}", cls="err"))
    changed = set(v["changed"]) | set(v["missing"])
    statuses = {f["path"]: f["status"] for f in v["files"]}
    buttons = [ds_button(f"Update changed ({len(changed)})",
                         f"$mode='selected'; @post('/ui/update/{repo_id}')", indicator="_upd", icon=reload_icon())]
    if v["all_present"]:
        buttons.append(ds_button("Re-download all", f"$mode='all'; @post('/ui/update/{repo_id}')",
                                 indicator="_updall", cls="ghost", icon=reload_icon()))
    form = file_list(
        v["files"], signals={"repo": repo_id},
        statuses=statuses, preselect=changed, submit_buttons=buttons,
    )
    head = [P(notice, cls="err")] if notice else []
    head.append(P(f"{len(changed)} file(s) changed or missing.", cls="muted"))
    return modal(f"Update {repo_id}", *head, form)


@rt("/ui/update/{repo_id:path}", methods=["GET"])
def ui_update(req, sess, repo_id: str):
    return show_modal(_update_modal(repo_id))


@rt("/ui/update/{repo_id:path}", methods=["POST"])
async def ui_update_apply(req, sess, repo_id: str):
    s = await _ds(req)
    if auth.csrf_ok(sess, s.get("csrf")):
        rec = store.get_archive(repo_id)
        if rec:
            selected = None if (s.get("mode") or "selected") == "all" else list(s.get("files") or [])
            try:
                jobs.manager.start_download(repo_id, rec["revision"], store_id=rec["store_id"], selected=selected)
            except (jobs.InsufficientSpace, jobs.Busy) as e:
                return show_modal(_update_modal(repo_id, notice=f"⚠️ {e}"))
    return modal_close()


@rt("/ui/jobs", methods=["GET"])
async def ui_jobs():
    return sse_stream(jobs_body)


def job_history_fragment():
    names = {s["id"]: s["name"] for s in store.list_stores()}
    rows = []
    for j in store.recent_jobs():
        badge = status_pill(j["status"])
        detail = j["error"] or ""
        if j["status"] == "retried" and j.get("retried_by"):
            detail = f"→ retried as {j['retried_by']}"
        retry = (ds_button("Retry", f"@post('/ui/jobs/{j['id']}/retry')",
                           indicator=_sig("rt", j["id"]), busy="Restarting…", cls="ghost")
                 if j["status"] == "error" else "")
        rows.append(Tr(
            Td(job_kind(j["type"])),
            Td(j["repo_id"], cls="mono wrap"),
            Td(names.get(j["store_id"]) or "—", cls="muted"),
            # error/retried detail is the status's title (hover) — no separate column
            Td(badge, **({"title": detail} if detail else {})),
            Td((j["updated_at"] or "")[:19].replace("T", " "), cls="muted mono"),
            Td(retry, cls="r"),
        ))
    body = (Table(Thead(Tr(Th("Type"), Th("Model"), Th("Store"), Th("Status"),
                           Th("Updated (UTC)"), Th("", cls="r"))), Tbody(*rows))
            if rows else P("No jobs yet.", cls="muted"))
    header = Div(
        H2("Job history"),
        ds_button("Clear finished", "@post('/ui/jobs/clear')",
                  indicator="_clearfin", busy="Clearing…", cls="ghost"),
        cls="section-head",
    )
    return Div(header, body,
               P("Finished jobs (done/error) are kept for 30 days, then pruned on "
                 "startup — or clear them now. Queued/running/paused jobs are kept "
                 "and resume after a restart.", cls="muted"),
               id="jobhistory")


@rt("/jobs")
def jobs_history_page(sess):
    return page(
        Div(H2("Live jobs"), jobs_panel(), cls="card"),
        Div(job_history_fragment(), cls="card"),
        sess=sess, active="jobs",
    )


@rt("/ui/jobs/clear", methods=["POST"])
async def ui_jobs_clear(req, sess):
    if await _ds_csrf_ok(req, sess):
        store.delete_finished_jobs()
        jobs.manager.clear_finished()
    return patch(job_history_fragment())


@rt("/ui/jobs/{job_id}/retry", methods=["POST"])
async def ui_job_retry(req, sess, job_id: str):
    if await _ds_csrf_ok(req, sess):
        try:
            jobs.manager.retry(job_id)
        except (jobs.InsufficientSpace, jobs.Busy):
            pass
    return patch(job_history_fragment())


@rt("/ui/archives", methods=["GET"])
async def ui_archives():
    return sse_stream(archives_body)


@rt("/ui/summary", methods=["GET"])
async def ui_summary():
    return sse_stream(summary_fragment)


@rt("/ui/check/{repo_id:path}", methods=["POST"])
async def ui_check(req, sess, repo_id: str):
    if await _ds_csrf_ok(req, sess):
        try:
            jobs.check_update(repo_id)
        except KeyError:
            pass
    return patch(archives_body())


@rt("/ui/check-all", methods=["POST"])
async def ui_check_all(req, sess):
    if await _ds_csrf_ok(req, sess):
        for a in store.list_archives():
            try:
                jobs.check_update(a["repo_id"])
            except Exception:
                pass
    return patch(archives_body())


@rt("/ui/delete/{repo_id:path}", methods=["POST"])
async def ui_delete(req, sess, repo_id: str):
    if await _ds_csrf_ok(req, sess):
        jobs.delete_archive(repo_id)
    return patch(archives_body())


# --- data stores ---------------------------------------------------------

def stores_body(notice: str | None = None):
    rows = []
    for s in store.list_stores():
        sid = s["id"]
        default_cell = (
            Span("default", cls="badge current") if s["is_default"]
            else ds_button("Make default", f"@post('/ui/stores/{sid}/default')",
                           indicator=_sig("sd", sid), cls="ghost")
        )
        try:
            free = util.human_size(util.free_space(s["path"]))
        except Exception:
            free = "—"
        actions = [
            ds_button("Import", f"@post('/ui/stores/{sid}/import')",
                      indicator=_sig("si", sid), busy="Importing…", cls="ghost"),
        ]
        # A store can be deleted only when it's non-default and empty.
        if not s["is_default"] and not s["n_models"]:
            actions.append(ds_button(
                "Delete",
                f"confirm(\"Remove store '{s['name']}'? (files on disk are left untouched)\") "
                f"&& @post('/ui/stores/{sid}/delete')",
                indicator=_sig("sx", sid), cls="danger"))
        rows.append(Tr(
            Td(s["name"]),
            Td(s["path"], cls="mono muted wrap"),
            Td(f"{s['n_models']}", cls="muted"),
            Td(free, cls="muted"),
            Td(default_cell),
            Td(Div(*actions, cls="actions")),
        ))
    table = Table(
        Thead(Tr(Th("Name"), Th("Path"), Th("Models"), Th("Free"), Th("Default"), Th("", cls="r"))),
        Tbody(*rows),
    )
    add = Div(
        Input(type="text", placeholder="name", cls="narrow mono", **{"data-bind": "sname"}),
        Input(type="text", placeholder="/absolute/path", cls="mono", **{"data-bind": "spath"}),
        ds_button("Add store", "@post('/ui/stores/add')", indicator="_addstore", busy="Adding…"),
        cls="row divider-top mt-[18px]", **{"data-signals": json.dumps({"sname": "", "spath": ""})},
    )
    head = [H2("Data stores")]
    if notice:
        head.append(P(notice, cls="muted"))
    return Div(*head, table, add,
               P("Import scans a store's folder and rebuilds the catalog from each "
                 "model's .hugger.json.", cls="muted"),
               id="stores-body")


@rt("/stores")
def stores_page(sess):
    return page(Div(stores_body(), cls="card"), sess=sess, active="stores")


@rt("/ui/stores/add", methods=["POST"])
async def ui_store_add(req, sess):
    s = await _ds(req)
    name, path = (s.get("sname") or "").strip(), (s.get("spath") or "").strip()
    if auth.csrf_ok(sess, s.get("csrf")) and name and path:
        from pathlib import Path as _P
        p = str(_P(path).expanduser())
        try:
            util.check_writable(p)  # creates the dir and verifies it's writable
        except OSError as e:
            return patch(stores_body(notice=f"⚠️ {path} is not writable: {e}"))
        try:
            store.add_store(name, p)  # rejects paths overlapping another store
        except ValueError as e:
            return patch(stores_body(notice=f"⚠️ {e}"))
    return patch(stores_body())


@rt("/ui/stores/{store_id}/import", methods=["POST"])
async def ui_store_import(req, sess, store_id: str):
    if await _ds_csrf_ok(req, sess):
        try:
            n = jobs.import_store(store_id)
            return patch(stores_body(notice=f"Imported {n} model(s)."))
        except KeyError:
            pass
    return patch(stores_body())


@rt("/ui/stores/{store_id}/default", methods=["POST"])
async def ui_store_default(req, sess, store_id: str):
    if await _ds_csrf_ok(req, sess):
        store.set_default_store(store_id)
    return patch(stores_body())


@rt("/ui/stores/{store_id}/delete", methods=["POST"])
async def ui_store_delete(req, sess, store_id: str):
    if await _ds_csrf_ok(req, sess) and store.store_model_count(store_id) == 0:
        store.delete_store(store_id)
    return patch(stores_body())


# --- settings ------------------------------------------------------------

@rt("/settings")
def settings(sess, msg: str = ""):
    note = P(msg, cls="muted") if msg else ""
    token_card = Div(
        H2("Extension API token"),
        P("Paste this into the hugger browser extension to authorize it. "
          "Keep it secret — it grants archive access.", cls="muted"),
        Label("Token", **{"for": "ext-token"}, cls="field-label"),
        Input(id="ext-token", type="text", value=cfg.api_token, readonly=True, cls="mono token-field"),
        Form(action_button("Rotate token", cls="danger", busy="Rotating…"),
             method="post", action="/settings/rotate-token"),
        cls="card",
    )
    src = hub.hf_token_source()
    src_label = {
        "ui": "A token is set (saved here).",
        "env": "Using a token from the environment (HF_TOKEN).",
        "none": "No token set — only public models are accessible.",
    }[src]
    hf_card = Div(
        H2("HuggingFace token"),
        P("Needed to download gated or private models. ", Span(src_label, cls="muted")),
        Form(
            Input(type="password", name="token", placeholder="hf_… (leave blank and Clear to remove)", cls="mono"),
            action_button("Save token", busy="Saving…"),
            method="post", action="/settings/hf-token", cls="row",
        ),
        (Form(action_button("Clear token", cls="danger", busy="Clearing…"), method="post", action="/settings/hf-token/clear")
         if src == "ui" else ""),
        cls="card",
    )
    pw_card = Div(
        H2("Change password"),
        Form(
            Input(type="password", name="current", placeholder="current password"),
            Input(type="password", name="new", placeholder="new password"),
            action_button("Update password", busy="Updating…"),
            method="post", action="/settings/password", cls="row",
        ),
        cls="card",
    )
    info = Div(
        H2("Server"),
        Dl(
            Dt("Version"), Dd(VERSION, cls="mono"),
            Dt("Archive dir"), Dd(str(ARCHIVE_DIR), cls="mono"),
            Dt("HTTPS-only mode"), Dd("on" if cfg.https_only else "off", cls="mono"),
            cls="server-grid",
        ),
        cls="card",
    )
    return page(note, token_card, hf_card, pw_card, info, sess=sess, active="settings")


@rt("/settings/hf-token", methods=["POST"])
def settings_hf_token(token: str = ""):
    hub.set_hf_token(token.strip() or None)
    msg = "HF+token+saved" if token.strip() else "HF+token+cleared"
    return RedirectResponse(f"/settings?msg={msg}", status_code=303)


@rt("/settings/hf-token/clear", methods=["POST"])
def settings_hf_token_clear():
    hub.set_hf_token(None)
    return RedirectResponse("/settings?msg=HF+token+cleared", status_code=303)


@rt("/settings/rotate-token", methods=["POST"])
def settings_rotate():
    auth.rotate_token()
    return RedirectResponse("/settings?msg=Token+rotated", status_code=303)


@rt("/settings/password", methods=["POST"])
def settings_password(current: str = "", new: str = ""):
    if not auth.verify_password(current):
        return RedirectResponse("/settings?msg=Current+password+incorrect", status_code=303)
    if len(new) < 6:
        return RedirectResponse("/settings?msg=New+password+too+short", status_code=303)
    auth.set_password(new)
    return RedirectResponse("/settings?msg=Password+updated", status_code=303)


# --- JSON API (extension; Bearer token via _before) ----------------------

@rt("/api/ping", methods=["GET"])
def api_ping():
    return JSONResponse({"ok": True, "version": VERSION})


@rt("/api/archive", methods=["POST"])
async def api_archive(req):
    body = {}
    try:
        body = await req.json()
    except Exception:
        form = await req.form()
        body = dict(form)
    repo_id = (body.get("repo_id") or "").strip()
    if not repo_id:
        return JSONResponse({"error": "repo_id required"}, status_code=400)
    revision = (body.get("revision") or "main").strip()
    store_id = (body.get("store_id") or "").strip() or None
    files = body.get("files") or None  # optional list of paths -> selective download
    if isinstance(files, str):
        files = [files]
    try:
        job = jobs.manager.start_download(repo_id, revision, store_id=store_id, selected=files)
    except jobs.InsufficientSpace as e:
        return JSONResponse({"error": str(e)}, status_code=507)
    return JSONResponse({"job_id": job.id, "repo_id": repo_id})


@rt("/api/files", methods=["GET"])
def api_files(req):
    """List a repo's files with sizes + whether each is already downloaded."""
    repo_id = (req.query_params.get("repo_id") or "").strip()
    revision = (req.query_params.get("revision") or "main").strip()
    if not repo_id:
        return JSONResponse({"error": "repo_id required"}, status_code=400)
    try:
        info = hub.repo_files(repo_id, revision)
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=502)
    statuses, _ = file_statuses(repo_id, info["files"])
    out = []
    for f in info["files"]:
        st = statuses[f["path"]]
        out.append({
            "path": f["path"], "size": f["size"],
            "downloaded": st == "downloaded",
            "downloading": st == "downloading",
        })
    return JSONResponse({"repo_id": repo_id, "sha": info["sha"], "files": out})


@rt("/api/verify/{repo_id:path}", methods=["GET"])
def api_verify(req):
    try:
        return JSONResponse(jobs.manager.verify(req.path_params["repo_id"]))
    except KeyError:
        return JSONResponse({"error": "not archived"}, status_code=404)
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=502)


@rt("/api/file-status", methods=["GET"])
def api_file_status(req):
    repo_id = (req.query_params.get("repo_id") or "").strip()
    path = (req.query_params.get("path") or "").strip()
    if not repo_id or not path:
        return JSONResponse({"error": "repo_id and path required"}, status_code=400)
    return JSONResponse(jobs.file_status(repo_id, path))


@rt("/api/stores/{store_id}/import", methods=["POST"])
def api_store_import(req):
    try:
        n = jobs.import_store(req.path_params["store_id"])
    except KeyError:
        return JSONResponse({"error": "store not found"}, status_code=404)
    return JSONResponse({"ok": True, "imported": n})


@rt("/api/status/{job_id}", methods=["GET"])
def api_status(job_id: str):
    job = jobs.manager.get(job_id)
    if not job:
        return JSONResponse({"error": "not found"}, status_code=404)
    return JSONResponse(job.as_dict())


@rt("/api/jobs/{job_id}/pause", methods=["POST"])
def api_job_pause(req):
    jobs.manager.pause(req.path_params["job_id"])
    return JSONResponse({"ok": True})


@rt("/api/jobs/{job_id}/resume", methods=["POST"])
def api_job_resume(req):
    jobs.manager.resume(req.path_params["job_id"])
    return JSONResponse({"ok": True})


@rt("/api/stores", methods=["GET"])
def api_stores():
    return JSONResponse({"stores": store.list_stores()})


@rt("/api/archives", methods=["GET"])
def api_archives():
    return JSONResponse({"archives": store.list_archives()})


@rt("/api/archive/{repo_id:path}", methods=["GET"])
def api_archive_status(req):
    """Whether a specific repo is archived — used by the extension to decide
    between offering Archive vs Remove/Update."""
    repo_id = req.path_params["repo_id"]
    rec = store.get_archive(repo_id)
    if not rec:
        return JSONResponse({"repo_id": repo_id, "archived": False})
    return JSONResponse({
        "repo_id": repo_id,
        "archived": True,
        "sha": rec["sha"],
        "size_bytes": rec["size_bytes"],
        "update_available": bool(rec["update_available"]),
    })


@rt("/api/archive/{repo_id:path}", methods=["DELETE"])
def api_archive_delete(req):
    repo_id = req.path_params["repo_id"]
    jobs.delete_archive(repo_id)
    return JSONResponse({"ok": True, "repo_id": repo_id})


# --- entrypoint ----------------------------------------------------------

def main() -> None:
    store.run_migrations()
    store.ensure_default_store(str(ARCHIVE_DIR))  # default store lives in ~/.hugger
    store.prune_jobs()  # drop finished jobs older than the retention window
    _bootstrap_password()
    jobs.manager.resume_pending()  # re-launch downloads/moves interrupted by a restart
    import uvicorn

    print(f"hugger {VERSION} → http://{cfg.host}:{cfg.port}")
    # The live panels hold long-lived SSE connections that never end on their own.
    # Run uvicorn ourselves so that, the moment shutdown begins, we wake every
    # stream (_live.begin_shutdown) — they return cleanly, the connections close,
    # and the server exits at once with no force-cancel traceback or hang.
    config = uvicorn.Config(app, host=cfg.host, port=cfg.port, timeout_graceful_shutdown=5)
    server = uvicorn.Server(config)

    async def _serve():
        _live.bind_loop(asyncio.get_running_loop())

        async def _watch_shutdown():
            while not server.should_exit:
                await asyncio.sleep(0.1)
            _live.begin_shutdown()

        watcher = asyncio.ensure_future(_watch_shutdown())
        try:
            await server.serve()
        finally:
            watcher.cancel()

    try:
        asyncio.run(_serve())
    except KeyboardInterrupt:
        pass  # uvicorn already shut down gracefully on the signal


if __name__ == "__main__":
    main()
