"""Runnable self-checks for the non-trivial pure logic. No framework needed:

    python -m tests.test_core      (or)     python tests/test_core.py
"""
import os
import tempfile
from pathlib import Path

# Point hugger at a throwaway home BEFORE importing it.
_TMP = tempfile.mkdtemp(prefix="hugger-test-")
os.environ["HUGGER_HOME"] = _TMP
os.environ["HUGGER_ARCHIVE_DIR"] = str(Path(_TMP) / "archives")

from hugger import store, jobs, hub  # noqa: E402
from hugger.app import human_size  # noqa: E402
from hugger import auth  # noqa: E402


def test_store_crud():
    store.run_migrations()
    sid = store.ensure_default_store(str(Path(_TMP) / "archives"))
    store.upsert_archive("org/model", "main", "abc12345", "/tmp/x", 2048, sid)
    rows = store.list_archives()
    assert len(rows) == 1 and rows[0]["repo_id"] == "org/model"
    assert rows[0]["update_available"] == 0 and rows[0]["store_id"] == sid

    store.set_update_status("org/model", "def67890", True)
    rec = store.get_archive("org/model")
    assert rec["update_available"] == 1 and rec["remote_sha"] == "def67890"

    # upsert again resets the update flag and keeps a single row.
    store.upsert_archive("org/model", "main", "def67890", "/tmp/x", 4096, sid)
    rec = store.get_archive("org/model")
    assert rec["update_available"] == 0 and rec["size_bytes"] == 4096
    assert len(store.list_archives()) == 1

    store.delete_archive("org/model")
    assert store.get_archive("org/model") is None


def test_human_size():
    assert human_size(0) == "0 B"
    assert human_size(512) == "512 B"
    assert human_size(1536) == "1.5 KB"
    assert human_size(5 * 1024 * 1024) == "5.0 MB"


def test_store_repo_path_cross_platform():
    p = jobs.store_repo_path("/data", "org/model")
    assert p.parts[-2:] == ("org", "model")  # uses OS separator, not literal "/"


def test_dir_size(tmp=None):
    d = Path(_TMP) / "sz"
    d.mkdir(parents=True, exist_ok=True)
    (d / "a.bin").write_bytes(b"x" * 100)
    (d / "b.bin").write_bytes(b"y" * 23)
    assert jobs._dir_size(d) == 123


def test_token_and_csrf():
    assert auth.verify_token(auth.cfg.api_token) is True
    assert auth.verify_token("wrong") is False
    assert auth.verify_token(None) is False
    sess = {}
    tok = auth.csrf_token(sess)
    assert auth.csrf_ok(sess, tok) is True
    assert auth.csrf_ok(sess, "nope") is False


def test_password_roundtrip():
    auth.set_password("hunter2")
    assert auth.verify_password("hunter2") is True
    assert auth.verify_password("wrong") is False


def test_password_stored_in_db_not_config():
    import json
    from hugger.config import CONFIG_PATH

    auth.set_password("dbpw1234", autogenerated=False)
    assert store.get_setting("password_hash") is not None
    cfg_data = json.loads(CONFIG_PATH.read_text())
    assert "password_hash" not in cfg_data  # pw is in the DB now


def test_autogenerated_flag():
    auth.set_password("temp-generated", autogenerated=True)
    assert auth.must_change_password() is True
    auth.set_password("chosen-one", autogenerated=False)
    assert auth.must_change_password() is False


def test_hf_token_setting():
    hub.set_hf_token(None)
    assert hub.hf_token_source() in ("none", "env")
    hub.set_hf_token("hf_abc123")
    assert hub.current_hf_token() == "hf_abc123"  # DB value wins
    assert hub.hf_token_source() == "ui"
    hub.set_hf_token(None)  # clear -> falls back to env (None in tests)
    assert hub.current_hf_token() == hub.cfg.hf_token
    assert hub.hf_token_source() in ("none", "env")


def test_settings_kv():
    assert store.get_setting("nope") is None
    store.set_setting("k", "v1")
    assert store.get_setting("k") == "v1"
    store.set_setting("k", "v2")  # upsert
    assert store.get_setting("k") == "v2"


def test_jobs_persistence():
    store.save_job({"id": "j1", "repo_id": "org/m", "status": "queued"})
    assert "j1" in [j["id"] for j in store.list_jobs(["queued", "running"])]
    store.save_job({"id": "j1", "repo_id": "org/m", "status": "running", "total_bytes": 100})
    store.save_job({"id": "j1", "repo_id": "org/m", "status": "done", "total_bytes": 100})
    assert "j1" not in [j["id"] for j in store.list_jobs(["queued", "running"])]
    assert "j1" in [j["id"] for j in store.list_jobs(["done"])]


def test_stores_crud():
    a = store.ensure_default_store(str(Path(_TMP) / "archives"))
    b = store.add_store("cold", str(Path(_TMP) / "cold"))
    names = {s["name"] for s in store.list_stores()}
    assert {"default", "cold"} <= names
    assert store.get_default_store()["id"] == a
    store.set_default_store(b)
    assert store.get_default_store()["id"] == b
    store.set_default_store(a)  # restore
    # empty, non-default store can be deleted
    store.delete_store(b)
    assert store.get_store(b) is None


def _make_archive(store_id, repo_id, files):
    st = store.get_store(store_id)
    p = jobs.store_repo_path(st["path"], repo_id)
    p.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (p / name).write_bytes(data)
    size = jobs._dir_size(p)
    store.upsert_archive(repo_id, "main", "sha-move", str(p), size, store_id)
    return p


def test_move_job_across_stores():
    import time
    a = store.ensure_default_store(str(Path(_TMP) / "archives"))
    b = store.add_store("dest", str(Path(_TMP) / "dest"))
    src = _make_archive(a, "org/mover", {"config.json": b"{}", "w.bin": b"x" * 2048})

    job = jobs.manager.start_move("org/mover", b)
    for _ in range(100):
        if jobs.manager.get(job.id).status in ("done", "error"):
            break
        time.sleep(0.05)
    j = jobs.manager.get(job.id)
    assert j.status == "done", j.error
    rec = store.get_archive("org/mover")
    assert rec["store_id"] == b
    dest = jobs.store_repo_path(store.get_store(b)["path"], "org/mover")
    assert (dest / "w.bin").stat().st_size == 2048
    assert not src.exists()  # source copy removed after the move
    store.delete_archive("org/mover")
    store.delete_store(b)


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    for fn in fns:
        fn()
        print(f"ok  {fn.__name__}")
    print(f"\nAll {len(fns)} checks passed.")
