"""Runnable self-checks for the non-trivial pure logic. No framework needed:

    python -m tests.test_core      (or)     python tests/test_core.py
"""
import os
import tempfile
from pathlib import Path

# Point hugger at a throwaway home BEFORE importing it.
_TMP = tempfile.mkdtemp(prefix="hugger-test-")
os.environ["HUGGER_HOME"] = _TMP
os.environ["HUGGER_ARCHIVE_DIR"] = str(Path(_TMP) / "archives")

from hugger import store, jobs, hub  # noqa: E402
from hugger.app import human_size  # noqa: E402
from hugger import auth  # noqa: E402


def test_store_crud():
    store.run_migrations()
    store.upsert_archive("org/model", "main", "abc12345", "/tmp/x", 2048)
    rows = store.list_archives()
    assert len(rows) == 1 and rows[0]["repo_id"] == "org/model"
    assert rows[0]["update_available"] == 0

    store.set_update_status("org/model", "def67890", True)
    rec = store.get_archive("org/model")
    assert rec["update_available"] == 1 and rec["remote_sha"] == "def67890"

    # upsert again resets the update flag and keeps a single row.
    store.upsert_archive("org/model", "main", "def67890", "/tmp/x", 4096)
    rec = store.get_archive("org/model")
    assert rec["update_available"] == 0 and rec["size_bytes"] == 4096
    assert len(store.list_archives()) == 1

    store.delete_archive("org/model")
    assert store.get_archive("org/model") is None


def test_human_size():
    assert human_size(0) == "0 B"
    assert human_size(512) == "512 B"
    assert human_size(1536) == "1.5 KB"
    assert human_size(5 * 1024 * 1024) == "5.0 MB"


def test_local_path_cross_platform():
    p = hub.local_path("org/model")
    assert p.parts[-2:] == ("org", "model")  # uses OS separator, not literal "/"


def test_dir_size(tmp=None):
    d = Path(_TMP) / "sz"
    d.mkdir(parents=True, exist_ok=True)
    (d / "a.bin").write_bytes(b"x" * 100)
    (d / "b.bin").write_bytes(b"y" * 23)
    assert jobs._dir_size(d) == 123


def test_token_and_csrf():
    assert auth.verify_token(auth.cfg.api_token) is True
    assert auth.verify_token("wrong") is False
    assert auth.verify_token(None) is False
    sess = {}
    tok = auth.csrf_token(sess)
    assert auth.csrf_ok(sess, tok) is True
    assert auth.csrf_ok(sess, "nope") is False


def test_password_roundtrip():
    auth.set_password("hunter2")
    assert auth.verify_password("hunter2") is True
    assert auth.verify_password("wrong") is False


def test_password_stored_in_db_not_config():
    import json
    from hugger.config import CONFIG_PATH

    auth.set_password("dbpw1234", autogenerated=False)
    assert store.get_setting("password_hash") is not None
    cfg_data = json.loads(CONFIG_PATH.read_text())
    assert "password_hash" not in cfg_data  # pw is in the DB now


def test_autogenerated_flag():
    auth.set_password("temp-generated", autogenerated=True)
    assert auth.must_change_password() is True
    auth.set_password("chosen-one", autogenerated=False)
    assert auth.must_change_password() is False


def test_settings_kv():
    assert store.get_setting("nope") is None
    store.set_setting("k", "v1")
    assert store.get_setting("k") == "v1"
    store.set_setting("k", "v2")  # upsert
    assert store.get_setting("k") == "v2"


def test_jobs_persistence():
    store.upsert_job("j1", "org/m", "main", "queued")
    active = [j["id"] for j in store.list_active_jobs()]
    assert "j1" in active
    store.upsert_job("j1", "org/m", "main", "downloading", 100, "sha")
    store.upsert_job("j1", "org/m", "main", "done", 100, "sha")
    assert "j1" not in [j["id"] for j in store.list_active_jobs()]


def test_resume_pending():
    import time
    from pathlib import Path

    # Seed a job that was mid-download when the process "stopped".
    store.upsert_job("rj1", "org/resume", "main", "downloading", 0, None)

    orig_meta, orig_dl = jobs.hub.repo_meta, jobs.hub.download
    jobs.hub.repo_meta = lambda r, rev="main": {"sha": "deadbeef", "total_size": 5, "n_files": 1}

    def fake_dl(r, rev, dest):
        Path(dest).mkdir(parents=True, exist_ok=True)
        (Path(dest) / "f.bin").write_bytes(b"x" * 5)
        return str(dest)

    jobs.hub.download = fake_dl
    try:
        jobs.manager.resume_pending()
        rec = None
        for _ in range(50):
            rec = store.get_archive("org/resume")
            if rec:
                break
            time.sleep(0.1)
        assert rec is not None and rec["sha"] == "deadbeef"
        assert "rj1" not in [j["id"] for j in store.list_active_jobs()]
    finally:
        jobs.hub.repo_meta, jobs.hub.download = orig_meta, orig_dl
        store.delete_archive("org/resume")


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    for fn in fns:
        fn()
        print(f"ok  {fn.__name__}")
    print(f"\nAll {len(fns)} checks passed.")
