# NixOS VM test: load the nix-built hugger OCI image into Docker and verify the
# container serves, authenticates, runs the forced-password-change flow, and that
# its token API works — using the same image CI pushes to the registry.
{ pkgs, self }:

let
  dockerImage = self.packages.${pkgs.stdenv.hostPlatform.system}.docker;
in
pkgs.testers.runNixOSTest {
  name = "hugger-docker";

  nodes.machine = { config, pkgs, ... }: {
    virtualisation.docker.enable = true;
    virtualisation.oci-containers = {
      backend = "docker";
      containers.hugger = {
        image = "hugger:latest";
        imageFile = dockerImage;
        ports = [ "7860:7860" ];
      };
    };
    environment.systemPackages = [ pkgs.curl pkgs.jq ];
    virtualisation.memorySize = 2048;
    virtualisation.diskSize = 6144;
    virtualisation.cores = 2;
  };

  testScript = ''
    start_all()
    machine.wait_for_unit("docker-hugger.service")

    # docker-proxy opens the port before the app is ready, so wait for the app
    # itself to answer rather than just the port.
    machine.wait_until_succeeds("curl -sf -o /dev/null http://127.0.0.1:7860/login", timeout=120)
    machine.succeed("test \"$(curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:7860/api/ping)\" = 401")

    # The container generated an initial password and forces a change on login.
    pw = machine.wait_until_succeeds(
        "docker logs hugger 2>&1 | grep -oP 'PASSWORD: \\K\\S+' | tail -1", timeout=60
    ).strip()
    assert pw, "no autogenerated password in container logs"

    redir = machine.succeed(
        f"curl -sS -c /tmp/jar -o /dev/null -w '%{{redirect_url}}' "
        f"--data 'password={pw}' http://127.0.0.1:7860/login"
    )
    assert "change-password" in redir, f"expected forced change, got {redir!r}"
    machine.succeed(
        "curl -sS -b /tmp/jar -c /tmp/jar -o /dev/null "
        "--data 'new=Sup3rSecret1&confirm=Sup3rSecret1' http://127.0.0.1:7860/change-password"
    )
    machine.succeed("curl -sS -b /tmp/jar http://127.0.0.1:7860/ | grep -q 'Recent activity'")

    # Token API works (read the token straight out of the container's /data).
    machine.succeed("docker cp hugger:/data/config.json /tmp/cfg.json")
    token = machine.succeed("jq -r .api_token /tmp/cfg.json").strip()
    machine.succeed(f"curl -sf -H 'Authorization: Bearer {token}' http://127.0.0.1:7860/api/ping | jq -e .ok")

    # /data is written (config.json copied out above implies the DB dir exists).
    machine.succeed("docker cp hugger:/data/hugger.db /tmp/hugger.db")
  '';
}
