# NixOS VM test: boot hugger, change the autogenerated password, then download a
# model from a fake HuggingFace Hub served over self-signed HTTPS that is trusted
# by the VM and reached via an /etc/hosts override of huggingface.co.
{ pkgs, self }:

let
  # CA + server cert for huggingface.co. The CA needs keyCertSign and the server
  # cert needs an explicit SAN + serverAuth for OpenSSL 3 / httpx to accept it.
  certs = pkgs.runCommand "hugger-test-certs" { nativeBuildInputs = [ pkgs.openssl ]; } ''
    mkdir -p $out
    openssl req -x509 -newkey rsa:2048 -nodes -keyout $out/ca.key -out $out/ca.crt \
      -subj "/CN=hugger Test CA" -days 3650 \
      -addext "basicConstraints=critical,CA:TRUE" \
      -addext "keyUsage=critical,keyCertSign,cRLSign"
    openssl req -newkey rsa:2048 -nodes -keyout $out/server.key -out $out/server.csr \
      -subj "/CN=huggingface.co" -addext "subjectAltName=DNS:huggingface.co"
    openssl x509 -req -in $out/server.csr -CA $out/ca.crt -CAkey $out/ca.key -CAcreateserial \
      -out $out/server.crt -days 3650 \
      -extfile <(printf "subjectAltName=DNS:huggingface.co\nkeyUsage=digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth")
  '';
in
pkgs.testers.runNixOSTest {
  name = "hugger";

  nodes.machine = { config, pkgs, ... }: {
    imports = [ self.nixosModules.default ];

    services.hugger = {
      enable = true;
      host = "127.0.0.1";
      port = 7860;
      extraEnvironment = {
        # Make httpx (huggingface_hub) trust our CA, included in the system bundle.
        SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
        HF_HUB_DOWNLOAD_TIMEOUT = "30";
      };
    };

    # Trust the test CA system-wide, and point huggingface.co at the fake hub.
    security.pki.certificateFiles = [ "${certs}/ca.crt" ];
    networking.hosts."127.0.0.1" = [ "huggingface.co" ];

    systemd.services.fake-hf-hub = {
      description = "Fake HuggingFace Hub (HTTPS)";
      wantedBy = [ "multi-user.target" ];
      before = [ "hugger.service" ];
      environment = {
        FAKE_HUB_HOST = "0.0.0.0";
        FAKE_HUB_PORT = "443";
        FAKE_HUB_CERT = "${certs}/server.crt";
        FAKE_HUB_KEY = "${certs}/server.key";
      };
      serviceConfig = {
        ExecStart = "${pkgs.python3}/bin/python ${./fake_hf_hub.py}";
        DynamicUser = true;
        AmbientCapabilities = [ "CAP_NET_BIND_SERVICE" ];
      };
    };

    environment.systemPackages = [ pkgs.curl pkgs.jq ];
    virtualisation.memorySize = 2048;
  };

  testScript = ''
    import json

    start_all()
    machine.wait_for_unit("fake-hf-hub.service")
    machine.wait_for_open_port(443)
    machine.wait_for_unit("hugger.service")
    machine.wait_for_open_port(7860)

    # The initial password is autogenerated and printed to the journal.
    pw = machine.succeed(
        "journalctl -u hugger -o cat | grep -oP 'PASSWORD: \\K\\S+' | tail -1"
    ).strip()
    assert pw, "no autogenerated password found in journal"

    # Logging in with it must force a password change.
    redir = machine.succeed(
        f"curl -sS -c /tmp/jar -o /dev/null -w '%{{redirect_url}}' "
        f"--data 'password={pw}' http://127.0.0.1:7860/login"
    )
    assert "change-password" in redir, f"expected forced change, got {redir!r}"

    # Change the password, then confirm the dashboard is reachable.
    machine.succeed(
        "curl -sS -b /tmp/jar -c /tmp/jar -o /dev/null "
        "--data 'new=Sup3rSecret1&confirm=Sup3rSecret1' "
        "http://127.0.0.1:7860/change-password"
    )
    machine.succeed("curl -sS -b /tmp/jar http://127.0.0.1:7860/ | grep -q 'Recent activity'")

    # Old (generated) password should no longer work.
    bad = machine.succeed(
        f"curl -sS -c /tmp/jar2 -o /dev/null -w '%{{redirect_url}}' "
        f"--data 'password={pw}' http://127.0.0.1:7860/login"
    )
    assert "error" in bad, f"old password should be rejected, got {bad!r}"

    # Download a model via the token API — this hits the fake hub over HTTPS as
    # huggingface.co, exercising the self-signed cert + hosts override + CA trust.
    token = machine.succeed("jq -r .api_token /var/lib/hugger/config.json").strip()
    resp = machine.succeed(
        f"curl -sS -H 'Authorization: Bearer {token}' -H 'Content-Type: application/json' "
        f"--data '{{\"repo_id\": \"test-org/tiny-model\"}}' http://127.0.0.1:7860/api/archive"
    )
    job_id = json.loads(resp)["job_id"]

    machine.wait_until_succeeds(
        f"curl -sS -H 'Authorization: Bearer {token}' "
        f"http://127.0.0.1:7860/api/status/{job_id} | jq -e '.status == \"done\"'",
        timeout=120,
    )

    # Files actually landed on disk and content is intact.
    machine.succeed("test -s /var/lib/hugger/archives/test-org/tiny-model/weights.bin")
    machine.succeed("grep -q tiny /var/lib/hugger/archives/test-org/tiny-model/config.json")

    # And the archive shows up in the authenticated API listing.
    machine.succeed(
        f"curl -sS -H 'Authorization: Bearer {token}' http://127.0.0.1:7860/api/archives "
        f"| jq -e '.archives[0].repo_id == \"test-org/tiny-model\"'"
    )
  '';
}
