-- Key/value app settings (password hash + autogenerated flag live here) and a
-- persisted jobs table so in-progress downloads survive restarts.
CREATE TABLE settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE jobs (
    id          TEXT PRIMARY KEY,
    repo_id     TEXT NOT NULL,
    revision    TEXT NOT NULL DEFAULT 'main',
    status      TEXT NOT NULL,        -- queued | downloading | done | error
    total_bytes INTEGER NOT NULL DEFAULT 0,
    sha         TEXT,
    error       TEXT,
    created_at  TEXT NOT NULL,
    updated_at  TEXT
);
